---
version: "3"
services:
  adminer:
    image: adminer:4.7
    environment:
      ADMINER_DESIGN: mancave
    depends_on:
      - db
    expose:
      - "10003:8080"
    restart: always
  backend:
    image: registry.pusilkom.com/ppsdm/simlitekkes-backend:develop
    env_file:
      - .env-develop
    ports:
      - "10001:8001"
  db:
    env_file:
      - .env-develop
    command: postgres -c 'max_connections=200'
    ports:
      - "10002:5432"