package com.pusilkom.base.model;

import java.io.Serializable;
import java.util.Date;

public class DokumenOrganisasi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.id_organisasi
     *
     * @mbg.generated
     */
    private Integer idOrganisasi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.nama_file
     *
     * @mbg.generated
     */
    private String namaFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.file_path
     *
     * @mbg.generated
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.timestamp_upload
     *
     * @mbg.generated
     */
    private Date timestampUpload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.user_upload
     *
     * @mbg.generated
     */
    private String userUpload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.id_jenis_dokumen
     *
     * @mbg.generated
     */
    private Integer idJenisDokumen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.nomor_dokumen
     *
     * @mbg.generated
     */
    private String nomorDokumen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.tahun_terbit
     *
     * @mbg.generated
     */
    private String tahunTerbit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dokumen_organisasi.judul
     *
     * @mbg.generated
     */
    private String judul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dokumen_organisasi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.id
     *
     * @return the value of dokumen_organisasi.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.id
     *
     * @param id the value for dokumen_organisasi.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.id_organisasi
     *
     * @return the value of dokumen_organisasi.id_organisasi
     *
     * @mbg.generated
     */
    public Integer getIdOrganisasi() {
        return idOrganisasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.id_organisasi
     *
     * @param idOrganisasi the value for dokumen_organisasi.id_organisasi
     *
     * @mbg.generated
     */
    public void setIdOrganisasi(Integer idOrganisasi) {
        this.idOrganisasi = idOrganisasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.nama_file
     *
     * @return the value of dokumen_organisasi.nama_file
     *
     * @mbg.generated
     */
    public String getNamaFile() {
        return namaFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.nama_file
     *
     * @param namaFile the value for dokumen_organisasi.nama_file
     *
     * @mbg.generated
     */
    public void setNamaFile(String namaFile) {
        this.namaFile = namaFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.file_path
     *
     * @return the value of dokumen_organisasi.file_path
     *
     * @mbg.generated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.file_path
     *
     * @param filePath the value for dokumen_organisasi.file_path
     *
     * @mbg.generated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.timestamp_upload
     *
     * @return the value of dokumen_organisasi.timestamp_upload
     *
     * @mbg.generated
     */
    public Date getTimestampUpload() {
        return timestampUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.timestamp_upload
     *
     * @param timestampUpload the value for dokumen_organisasi.timestamp_upload
     *
     * @mbg.generated
     */
    public void setTimestampUpload(Date timestampUpload) {
        this.timestampUpload = timestampUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.user_upload
     *
     * @return the value of dokumen_organisasi.user_upload
     *
     * @mbg.generated
     */
    public String getUserUpload() {
        return userUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.user_upload
     *
     * @param userUpload the value for dokumen_organisasi.user_upload
     *
     * @mbg.generated
     */
    public void setUserUpload(String userUpload) {
        this.userUpload = userUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.id_jenis_dokumen
     *
     * @return the value of dokumen_organisasi.id_jenis_dokumen
     *
     * @mbg.generated
     */
    public Integer getIdJenisDokumen() {
        return idJenisDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.id_jenis_dokumen
     *
     * @param idJenisDokumen the value for dokumen_organisasi.id_jenis_dokumen
     *
     * @mbg.generated
     */
    public void setIdJenisDokumen(Integer idJenisDokumen) {
        this.idJenisDokumen = idJenisDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.nomor_dokumen
     *
     * @return the value of dokumen_organisasi.nomor_dokumen
     *
     * @mbg.generated
     */
    public String getNomorDokumen() {
        return nomorDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.nomor_dokumen
     *
     * @param nomorDokumen the value for dokumen_organisasi.nomor_dokumen
     *
     * @mbg.generated
     */
    public void setNomorDokumen(String nomorDokumen) {
        this.nomorDokumen = nomorDokumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.tahun_terbit
     *
     * @return the value of dokumen_organisasi.tahun_terbit
     *
     * @mbg.generated
     */
    public String getTahunTerbit() {
        return tahunTerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.tahun_terbit
     *
     * @param tahunTerbit the value for dokumen_organisasi.tahun_terbit
     *
     * @mbg.generated
     */
    public void setTahunTerbit(String tahunTerbit) {
        this.tahunTerbit = tahunTerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dokumen_organisasi.judul
     *
     * @return the value of dokumen_organisasi.judul
     *
     * @mbg.generated
     */
    public String getJudul() {
        return judul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dokumen_organisasi.judul
     *
     * @param judul the value for dokumen_organisasi.judul
     *
     * @mbg.generated
     */
    public void setJudul(String judul) {
        this.judul = judul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dokumen_organisasi
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DokumenOrganisasi other = (DokumenOrganisasi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdOrganisasi() == null ? other.getIdOrganisasi() == null : this.getIdOrganisasi().equals(other.getIdOrganisasi()))
            && (this.getNamaFile() == null ? other.getNamaFile() == null : this.getNamaFile().equals(other.getNamaFile()))
            && (this.getFilePath() == null ? other.getFilePath() == null : this.getFilePath().equals(other.getFilePath()))
            && (this.getTimestampUpload() == null ? other.getTimestampUpload() == null : this.getTimestampUpload().equals(other.getTimestampUpload()))
            && (this.getUserUpload() == null ? other.getUserUpload() == null : this.getUserUpload().equals(other.getUserUpload()))
            && (this.getIdJenisDokumen() == null ? other.getIdJenisDokumen() == null : this.getIdJenisDokumen().equals(other.getIdJenisDokumen()))
            && (this.getNomorDokumen() == null ? other.getNomorDokumen() == null : this.getNomorDokumen().equals(other.getNomorDokumen()))
            && (this.getTahunTerbit() == null ? other.getTahunTerbit() == null : this.getTahunTerbit().equals(other.getTahunTerbit()))
            && (this.getJudul() == null ? other.getJudul() == null : this.getJudul().equals(other.getJudul()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dokumen_organisasi
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdOrganisasi() == null) ? 0 : getIdOrganisasi().hashCode());
        result = prime * result + ((getNamaFile() == null) ? 0 : getNamaFile().hashCode());
        result = prime * result + ((getFilePath() == null) ? 0 : getFilePath().hashCode());
        result = prime * result + ((getTimestampUpload() == null) ? 0 : getTimestampUpload().hashCode());
        result = prime * result + ((getUserUpload() == null) ? 0 : getUserUpload().hashCode());
        result = prime * result + ((getIdJenisDokumen() == null) ? 0 : getIdJenisDokumen().hashCode());
        result = prime * result + ((getNomorDokumen() == null) ? 0 : getNomorDokumen().hashCode());
        result = prime * result + ((getTahunTerbit() == null) ? 0 : getTahunTerbit().hashCode());
        result = prime * result + ((getJudul() == null) ? 0 : getJudul().hashCode());
        return result;
    }
}