package com.pusilkom.base.model;

import java.io.Serializable;

public class JenisMitra implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jenis_mitra.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jenis_mitra.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jenis_mitra
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jenis_mitra.id
     *
     * @return the value of jenis_mitra.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jenis_mitra.id
     *
     * @param id the value for jenis_mitra.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jenis_mitra.nama
     *
     * @return the value of jenis_mitra.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jenis_mitra.nama
     *
     * @param nama the value for jenis_mitra.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jenis_mitra
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JenisMitra other = (JenisMitra) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jenis_mitra
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        return result;
    }
}