package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class KomentarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table komentar
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table komentar
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table komentar
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public KomentarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table komentar
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNull() {
            addCriterion("id_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNotNull() {
            addCriterion("id_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianEqualTo(Integer value) {
            addCriterion("id_penelitian =", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotEqualTo(Integer value) {
            addCriterion("id_penelitian <>", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThan(Integer value) {
            addCriterion("id_penelitian >", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian >=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThan(Integer value) {
            addCriterion("id_penelitian <", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian <=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIn(List<Integer> values) {
            addCriterion("id_penelitian in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotIn(List<Integer> values) {
            addCriterion("id_penelitian not in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian not between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanIsNull() {
            addCriterion("id_bagian_usulan is null");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanIsNotNull() {
            addCriterion("id_bagian_usulan is not null");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanEqualTo(Integer value) {
            addCriterion("id_bagian_usulan =", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanNotEqualTo(Integer value) {
            addCriterion("id_bagian_usulan <>", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanGreaterThan(Integer value) {
            addCriterion("id_bagian_usulan >", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_bagian_usulan >=", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanLessThan(Integer value) {
            addCriterion("id_bagian_usulan <", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanLessThanOrEqualTo(Integer value) {
            addCriterion("id_bagian_usulan <=", value, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanIn(List<Integer> values) {
            addCriterion("id_bagian_usulan in", values, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanNotIn(List<Integer> values) {
            addCriterion("id_bagian_usulan not in", values, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanBetween(Integer value1, Integer value2) {
            addCriterion("id_bagian_usulan between", value1, value2, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andIdBagianUsulanNotBetween(Integer value1, Integer value2) {
            addCriterion("id_bagian_usulan not between", value1, value2, "idBagianUsulan");
            return (Criteria) this;
        }

        public Criteria andKomentarIsNull() {
            addCriterion("komentar is null");
            return (Criteria) this;
        }

        public Criteria andKomentarIsNotNull() {
            addCriterion("komentar is not null");
            return (Criteria) this;
        }

        public Criteria andKomentarEqualTo(String value) {
            addCriterion("komentar =", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotEqualTo(String value) {
            addCriterion("komentar <>", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarGreaterThan(String value) {
            addCriterion("komentar >", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarGreaterThanOrEqualTo(String value) {
            addCriterion("komentar >=", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLessThan(String value) {
            addCriterion("komentar <", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLessThanOrEqualTo(String value) {
            addCriterion("komentar <=", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLike(String value) {
            addCriterion("komentar like", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotLike(String value) {
            addCriterion("komentar not like", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarIn(List<String> values) {
            addCriterion("komentar in", values, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotIn(List<String> values) {
            addCriterion("komentar not in", values, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarBetween(String value1, String value2) {
            addCriterion("komentar between", value1, value2, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotBetween(String value1, String value2) {
            addCriterion("komentar not between", value1, value2, "komentar");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIsNull() {
            addCriterion("timestamp_update is null");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIsNotNull() {
            addCriterion("timestamp_update is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateEqualTo(Date value) {
            addCriterion("timestamp_update =", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotEqualTo(Date value) {
            addCriterion("timestamp_update <>", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateGreaterThan(Date value) {
            addCriterion("timestamp_update >", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp_update >=", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateLessThan(Date value) {
            addCriterion("timestamp_update <", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateLessThanOrEqualTo(Date value) {
            addCriterion("timestamp_update <=", value, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateIn(List<Date> values) {
            addCriterion("timestamp_update in", values, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotIn(List<Date> values) {
            addCriterion("timestamp_update not in", values, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateBetween(Date value1, Date value2) {
            addCriterion("timestamp_update between", value1, value2, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andTimestampUpdateNotBetween(Date value1, Date value2) {
            addCriterion("timestamp_update not between", value1, value2, "timestampUpdate");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNull() {
            addCriterion("id_user is null");
            return (Criteria) this;
        }

        public Criteria andIdUserIsNotNull() {
            addCriterion("id_user is not null");
            return (Criteria) this;
        }

        public Criteria andIdUserEqualTo(Integer value) {
            addCriterion("id_user =", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotEqualTo(Integer value) {
            addCriterion("id_user <>", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThan(Integer value) {
            addCriterion("id_user >", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_user >=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThan(Integer value) {
            addCriterion("id_user <", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserLessThanOrEqualTo(Integer value) {
            addCriterion("id_user <=", value, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserIn(List<Integer> values) {
            addCriterion("id_user in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotIn(List<Integer> values) {
            addCriterion("id_user not in", values, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserBetween(Integer value1, Integer value2) {
            addCriterion("id_user between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andIdUserNotBetween(Integer value1, Integer value2) {
            addCriterion("id_user not between", value1, value2, "idUser");
            return (Criteria) this;
        }

        public Criteria andKomentarLikeInsensitive(String value) {
            addCriterion("upper(komentar) like", value.toUpperCase(), "komentar");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table komentar
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table komentar
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}