package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.List;

public class KriteriaPenilaianPenelitianExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public KriteriaPenilaianPenelitianExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdPenelitianIsNull() {
            addCriterion("id_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNotNull() {
            addCriterion("id_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianEqualTo(Integer value) {
            addCriterion("id_penelitian =", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotEqualTo(Integer value) {
            addCriterion("id_penelitian <>", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThan(Integer value) {
            addCriterion("id_penelitian >", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian >=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThan(Integer value) {
            addCriterion("id_penelitian <", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian <=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIn(List<Integer> values) {
            addCriterion("id_penelitian in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotIn(List<Integer> values) {
            addCriterion("id_penelitian not in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian not between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianIsNull() {
            addCriterion("id_kriteria_penilaian is null");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianIsNotNull() {
            addCriterion("id_kriteria_penilaian is not null");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianEqualTo(Integer value) {
            addCriterion("id_kriteria_penilaian =", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianNotEqualTo(Integer value) {
            addCriterion("id_kriteria_penilaian <>", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianGreaterThan(Integer value) {
            addCriterion("id_kriteria_penilaian >", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_kriteria_penilaian >=", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianLessThan(Integer value) {
            addCriterion("id_kriteria_penilaian <", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianLessThanOrEqualTo(Integer value) {
            addCriterion("id_kriteria_penilaian <=", value, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianIn(List<Integer> values) {
            addCriterion("id_kriteria_penilaian in", values, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianNotIn(List<Integer> values) {
            addCriterion("id_kriteria_penilaian not in", values, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianBetween(Integer value1, Integer value2) {
            addCriterion("id_kriteria_penilaian between", value1, value2, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdKriteriaPenilaianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_kriteria_penilaian not between", value1, value2, "idKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianIsNull() {
            addCriterion("id_pilihan_kriteria_penilaian is null");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianIsNotNull() {
            addCriterion("id_pilihan_kriteria_penilaian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianEqualTo(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian =", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianNotEqualTo(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian <>", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianGreaterThan(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian >", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian >=", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianLessThan(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian <", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianLessThanOrEqualTo(Integer value) {
            addCriterion("id_pilihan_kriteria_penilaian <=", value, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianIn(List<Integer> values) {
            addCriterion("id_pilihan_kriteria_penilaian in", values, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianNotIn(List<Integer> values) {
            addCriterion("id_pilihan_kriteria_penilaian not in", values, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianBetween(Integer value1, Integer value2) {
            addCriterion("id_pilihan_kriteria_penilaian between", value1, value2, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andIdPilihanKriteriaPenilaianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_pilihan_kriteria_penilaian not between", value1, value2, "idPilihanKriteriaPenilaian");
            return (Criteria) this;
        }

        public Criteria andKomentarIsNull() {
            addCriterion("komentar is null");
            return (Criteria) this;
        }

        public Criteria andKomentarIsNotNull() {
            addCriterion("komentar is not null");
            return (Criteria) this;
        }

        public Criteria andKomentarEqualTo(String value) {
            addCriterion("komentar =", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotEqualTo(String value) {
            addCriterion("komentar <>", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarGreaterThan(String value) {
            addCriterion("komentar >", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarGreaterThanOrEqualTo(String value) {
            addCriterion("komentar >=", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLessThan(String value) {
            addCriterion("komentar <", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLessThanOrEqualTo(String value) {
            addCriterion("komentar <=", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLike(String value) {
            addCriterion("komentar like", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotLike(String value) {
            addCriterion("komentar not like", value, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarIn(List<String> values) {
            addCriterion("komentar in", values, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotIn(List<String> values) {
            addCriterion("komentar not in", values, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarBetween(String value1, String value2) {
            addCriterion("komentar between", value1, value2, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarNotBetween(String value1, String value2) {
            addCriterion("komentar not between", value1, value2, "komentar");
            return (Criteria) this;
        }

        public Criteria andKomentarLikeInsensitive(String value) {
            addCriterion("upper(komentar) like", value.toUpperCase(), "komentar");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kriteria_penilaian_penelitian
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}