package com.pusilkom.base.model;

import java.io.Serializable;
import java.util.Date;

public class LogAktivitas implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_aktivitas.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_aktivitas.timestamp_aktivitas
     *
     * @mbg.generated
     */
    private Date timestampAktivitas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_aktivitas.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_aktivitas.request
     *
     * @mbg.generated
     */
    private String request;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_aktivitas.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_aktivitas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_aktivitas.username
     *
     * @return the value of log_aktivitas.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_aktivitas.username
     *
     * @param username the value for log_aktivitas.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_aktivitas.timestamp_aktivitas
     *
     * @return the value of log_aktivitas.timestamp_aktivitas
     *
     * @mbg.generated
     */
    public Date getTimestampAktivitas() {
        return timestampAktivitas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_aktivitas.timestamp_aktivitas
     *
     * @param timestampAktivitas the value for log_aktivitas.timestamp_aktivitas
     *
     * @mbg.generated
     */
    public void setTimestampAktivitas(Date timestampAktivitas) {
        this.timestampAktivitas = timestampAktivitas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_aktivitas.method
     *
     * @return the value of log_aktivitas.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_aktivitas.method
     *
     * @param method the value for log_aktivitas.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_aktivitas.request
     *
     * @return the value of log_aktivitas.request
     *
     * @mbg.generated
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_aktivitas.request
     *
     * @param request the value for log_aktivitas.request
     *
     * @mbg.generated
     */
    public void setRequest(String request) {
        this.request = request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_aktivitas.url
     *
     * @return the value of log_aktivitas.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_aktivitas.url
     *
     * @param url the value for log_aktivitas.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_aktivitas
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LogAktivitas other = (LogAktivitas) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getTimestampAktivitas() == null ? other.getTimestampAktivitas() == null : this.getTimestampAktivitas().equals(other.getTimestampAktivitas()))
            && (this.getMethod() == null ? other.getMethod() == null : this.getMethod().equals(other.getMethod()))
            && (this.getRequest() == null ? other.getRequest() == null : this.getRequest().equals(other.getRequest()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_aktivitas
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getTimestampAktivitas() == null) ? 0 : getTimestampAktivitas().hashCode());
        result = prime * result + ((getMethod() == null) ? 0 : getMethod().hashCode());
        result = prime * result + ((getRequest() == null) ? 0 : getRequest().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        return result;
    }
}