package com.pusilkom.base.model;

import java.io.Serializable;

public class Organisasi implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.id_topik
     *
     * @mbg.generated
     */
    private Integer idTopik;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.no_sk_pendirian
     *
     * @mbg.generated
     */
    private String noSkPendirian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.alamat
     *
     * @mbg.generated
     */
    private String alamat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.no_telp
     *
     * @mbg.generated
     */
    private String noTelp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.no_fax
     *
     * @mbg.generated
     */
    private String noFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.nama_jabatan_kepala
     *
     * @mbg.generated
     */
    private String namaJabatanKepala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.nidn_pejabat_kepala
     *
     * @mbg.generated
     */
    private String nidnPejabatKepala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.nama_pejabat_kepala
     *
     * @mbg.generated
     */
    private String namaPejabatKepala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.jenis_kelamin
     *
     * @mbg.generated
     */
    private String jenisKelamin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.jenjang_pendidikan
     *
     * @mbg.generated
     */
    private String jenjangPendidikan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.is_poltekkes
     *
     * @mbg.generated
     */
    private Boolean isPoltekkes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.klasifikasi
     *
     * @mbg.generated
     */
    private Short klasifikasi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organisasi.kode_pddikti
     *
     * @mbg.generated
     */
    private String kodePddikti;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.id
     *
     * @return the value of organisasi.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.id
     *
     * @param id the value for organisasi.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.id_topik
     *
     * @return the value of organisasi.id_topik
     *
     * @mbg.generated
     */
    public Integer getIdTopik() {
        return idTopik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.id_topik
     *
     * @param idTopik the value for organisasi.id_topik
     *
     * @mbg.generated
     */
    public void setIdTopik(Integer idTopik) {
        this.idTopik = idTopik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.nama
     *
     * @return the value of organisasi.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.nama
     *
     * @param nama the value for organisasi.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.no_sk_pendirian
     *
     * @return the value of organisasi.no_sk_pendirian
     *
     * @mbg.generated
     */
    public String getNoSkPendirian() {
        return noSkPendirian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.no_sk_pendirian
     *
     * @param noSkPendirian the value for organisasi.no_sk_pendirian
     *
     * @mbg.generated
     */
    public void setNoSkPendirian(String noSkPendirian) {
        this.noSkPendirian = noSkPendirian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.alamat
     *
     * @return the value of organisasi.alamat
     *
     * @mbg.generated
     */
    public String getAlamat() {
        return alamat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.alamat
     *
     * @param alamat the value for organisasi.alamat
     *
     * @mbg.generated
     */
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.no_telp
     *
     * @return the value of organisasi.no_telp
     *
     * @mbg.generated
     */
    public String getNoTelp() {
        return noTelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.no_telp
     *
     * @param noTelp the value for organisasi.no_telp
     *
     * @mbg.generated
     */
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.no_fax
     *
     * @return the value of organisasi.no_fax
     *
     * @mbg.generated
     */
    public String getNoFax() {
        return noFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.no_fax
     *
     * @param noFax the value for organisasi.no_fax
     *
     * @mbg.generated
     */
    public void setNoFax(String noFax) {
        this.noFax = noFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.email
     *
     * @return the value of organisasi.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.email
     *
     * @param email the value for organisasi.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.nama_jabatan_kepala
     *
     * @return the value of organisasi.nama_jabatan_kepala
     *
     * @mbg.generated
     */
    public String getNamaJabatanKepala() {
        return namaJabatanKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.nama_jabatan_kepala
     *
     * @param namaJabatanKepala the value for organisasi.nama_jabatan_kepala
     *
     * @mbg.generated
     */
    public void setNamaJabatanKepala(String namaJabatanKepala) {
        this.namaJabatanKepala = namaJabatanKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.nidn_pejabat_kepala
     *
     * @return the value of organisasi.nidn_pejabat_kepala
     *
     * @mbg.generated
     */
    public String getNidnPejabatKepala() {
        return nidnPejabatKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.nidn_pejabat_kepala
     *
     * @param nidnPejabatKepala the value for organisasi.nidn_pejabat_kepala
     *
     * @mbg.generated
     */
    public void setNidnPejabatKepala(String nidnPejabatKepala) {
        this.nidnPejabatKepala = nidnPejabatKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.nama_pejabat_kepala
     *
     * @return the value of organisasi.nama_pejabat_kepala
     *
     * @mbg.generated
     */
    public String getNamaPejabatKepala() {
        return namaPejabatKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.nama_pejabat_kepala
     *
     * @param namaPejabatKepala the value for organisasi.nama_pejabat_kepala
     *
     * @mbg.generated
     */
    public void setNamaPejabatKepala(String namaPejabatKepala) {
        this.namaPejabatKepala = namaPejabatKepala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.jenis_kelamin
     *
     * @return the value of organisasi.jenis_kelamin
     *
     * @mbg.generated
     */
    public String getJenisKelamin() {
        return jenisKelamin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.jenis_kelamin
     *
     * @param jenisKelamin the value for organisasi.jenis_kelamin
     *
     * @mbg.generated
     */
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.jenjang_pendidikan
     *
     * @return the value of organisasi.jenjang_pendidikan
     *
     * @mbg.generated
     */
    public String getJenjangPendidikan() {
        return jenjangPendidikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.jenjang_pendidikan
     *
     * @param jenjangPendidikan the value for organisasi.jenjang_pendidikan
     *
     * @mbg.generated
     */
    public void setJenjangPendidikan(String jenjangPendidikan) {
        this.jenjangPendidikan = jenjangPendidikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.is_poltekkes
     *
     * @return the value of organisasi.is_poltekkes
     *
     * @mbg.generated
     */
    public Boolean getIsPoltekkes() {
        return isPoltekkes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.is_poltekkes
     *
     * @param isPoltekkes the value for organisasi.is_poltekkes
     *
     * @mbg.generated
     */
    public void setIsPoltekkes(Boolean isPoltekkes) {
        this.isPoltekkes = isPoltekkes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.klasifikasi
     *
     * @return the value of organisasi.klasifikasi
     *
     * @mbg.generated
     */
    public Short getKlasifikasi() {
        return klasifikasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.klasifikasi
     *
     * @param klasifikasi the value for organisasi.klasifikasi
     *
     * @mbg.generated
     */
    public void setKlasifikasi(Short klasifikasi) {
        this.klasifikasi = klasifikasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.website
     *
     * @return the value of organisasi.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.website
     *
     * @param website the value for organisasi.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organisasi.kode_pddikti
     *
     * @return the value of organisasi.kode_pddikti
     *
     * @mbg.generated
     */
    public String getKodePddikti() {
        return kodePddikti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organisasi.kode_pddikti
     *
     * @param kodePddikti the value for organisasi.kode_pddikti
     *
     * @mbg.generated
     */
    public void setKodePddikti(String kodePddikti) {
        this.kodePddikti = kodePddikti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Organisasi other = (Organisasi) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdTopik() == null ? other.getIdTopik() == null : this.getIdTopik().equals(other.getIdTopik()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getNoSkPendirian() == null ? other.getNoSkPendirian() == null : this.getNoSkPendirian().equals(other.getNoSkPendirian()))
            && (this.getAlamat() == null ? other.getAlamat() == null : this.getAlamat().equals(other.getAlamat()))
            && (this.getNoTelp() == null ? other.getNoTelp() == null : this.getNoTelp().equals(other.getNoTelp()))
            && (this.getNoFax() == null ? other.getNoFax() == null : this.getNoFax().equals(other.getNoFax()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getNamaJabatanKepala() == null ? other.getNamaJabatanKepala() == null : this.getNamaJabatanKepala().equals(other.getNamaJabatanKepala()))
            && (this.getNidnPejabatKepala() == null ? other.getNidnPejabatKepala() == null : this.getNidnPejabatKepala().equals(other.getNidnPejabatKepala()))
            && (this.getNamaPejabatKepala() == null ? other.getNamaPejabatKepala() == null : this.getNamaPejabatKepala().equals(other.getNamaPejabatKepala()))
            && (this.getJenisKelamin() == null ? other.getJenisKelamin() == null : this.getJenisKelamin().equals(other.getJenisKelamin()))
            && (this.getJenjangPendidikan() == null ? other.getJenjangPendidikan() == null : this.getJenjangPendidikan().equals(other.getJenjangPendidikan()))
            && (this.getIsPoltekkes() == null ? other.getIsPoltekkes() == null : this.getIsPoltekkes().equals(other.getIsPoltekkes()))
            && (this.getKlasifikasi() == null ? other.getKlasifikasi() == null : this.getKlasifikasi().equals(other.getKlasifikasi()))
            && (this.getWebsite() == null ? other.getWebsite() == null : this.getWebsite().equals(other.getWebsite()))
            && (this.getKodePddikti() == null ? other.getKodePddikti() == null : this.getKodePddikti().equals(other.getKodePddikti()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdTopik() == null) ? 0 : getIdTopik().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getNoSkPendirian() == null) ? 0 : getNoSkPendirian().hashCode());
        result = prime * result + ((getAlamat() == null) ? 0 : getAlamat().hashCode());
        result = prime * result + ((getNoTelp() == null) ? 0 : getNoTelp().hashCode());
        result = prime * result + ((getNoFax() == null) ? 0 : getNoFax().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getNamaJabatanKepala() == null) ? 0 : getNamaJabatanKepala().hashCode());
        result = prime * result + ((getNidnPejabatKepala() == null) ? 0 : getNidnPejabatKepala().hashCode());
        result = prime * result + ((getNamaPejabatKepala() == null) ? 0 : getNamaPejabatKepala().hashCode());
        result = prime * result + ((getJenisKelamin() == null) ? 0 : getJenisKelamin().hashCode());
        result = prime * result + ((getJenjangPendidikan() == null) ? 0 : getJenjangPendidikan().hashCode());
        result = prime * result + ((getIsPoltekkes() == null) ? 0 : getIsPoltekkes().hashCode());
        result = prime * result + ((getKlasifikasi() == null) ? 0 : getKlasifikasi().hashCode());
        result = prime * result + ((getWebsite() == null) ? 0 : getWebsite().hashCode());
        result = prime * result + ((getKodePddikti() == null) ? 0 : getKodePddikti().hashCode());
        return result;
    }
}