package com.pusilkom.base.model;

import java.io.Serializable;

public class Penelitian implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_topik
     *
     * @mbg.generated
     */
    private Integer idTopik;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_skema_penelitian
     *
     * @mbg.generated
     */
    private Integer idSkemaPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_rumpun_ilmu
     *
     * @mbg.generated
     */
    private Integer idRumpunIlmu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    private Integer idTingkatKesiapanTeknologi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_tingkat_kesiapan_teknologi_target
     *
     * @mbg.generated
     */
    private Integer idTingkatKesiapanTeknologiTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.judul
     *
     * @mbg.generated
     */
    private String judul;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.ringkasan
     *
     * @mbg.generated
     */
    private String ringkasan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.tahun_usulan
     *
     * @mbg.generated
     */
    private String tahunUsulan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.tahun_mulai_pelaksanaan
     *
     * @mbg.generated
     */
    private String tahunMulaiPelaksanaan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.tahun_selesai_pelaksanaan
     *
     * @mbg.generated
     */
    private String tahunSelesaiPelaksanaan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.latar_belakang
     *
     * @mbg.generated
     */
    private String latarBelakang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.tinjauan_pustaka
     *
     * @mbg.generated
     */
    private String tinjauanPustaka;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.metode
     *
     * @mbg.generated
     */
    private String metode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.daftar_pustaka
     *
     * @mbg.generated
     */
    private String daftarPustaka;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_reviewer_skema
     *
     * @mbg.generated
     */
    private Integer idReviewerSkema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.lokasi_penelitian
     *
     * @mbg.generated
     */
    private String lokasiPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column penelitian.id_kelompok_tkt
     *
     * @mbg.generated
     */
    private Integer idKelompokTkt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table penelitian
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id
     *
     * @return the value of penelitian.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id
     *
     * @param id the value for penelitian.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_topik
     *
     * @return the value of penelitian.id_topik
     *
     * @mbg.generated
     */
    public Integer getIdTopik() {
        return idTopik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_topik
     *
     * @param idTopik the value for penelitian.id_topik
     *
     * @mbg.generated
     */
    public void setIdTopik(Integer idTopik) {
        this.idTopik = idTopik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_skema_penelitian
     *
     * @return the value of penelitian.id_skema_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdSkemaPenelitian() {
        return idSkemaPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_skema_penelitian
     *
     * @param idSkemaPenelitian the value for penelitian.id_skema_penelitian
     *
     * @mbg.generated
     */
    public void setIdSkemaPenelitian(Integer idSkemaPenelitian) {
        this.idSkemaPenelitian = idSkemaPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_rumpun_ilmu
     *
     * @return the value of penelitian.id_rumpun_ilmu
     *
     * @mbg.generated
     */
    public Integer getIdRumpunIlmu() {
        return idRumpunIlmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_rumpun_ilmu
     *
     * @param idRumpunIlmu the value for penelitian.id_rumpun_ilmu
     *
     * @mbg.generated
     */
    public void setIdRumpunIlmu(Integer idRumpunIlmu) {
        this.idRumpunIlmu = idRumpunIlmu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_tingkat_kesiapan_teknologi
     *
     * @return the value of penelitian.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    public Integer getIdTingkatKesiapanTeknologi() {
        return idTingkatKesiapanTeknologi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_tingkat_kesiapan_teknologi
     *
     * @param idTingkatKesiapanTeknologi the value for penelitian.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    public void setIdTingkatKesiapanTeknologi(Integer idTingkatKesiapanTeknologi) {
        this.idTingkatKesiapanTeknologi = idTingkatKesiapanTeknologi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_tingkat_kesiapan_teknologi_target
     *
     * @return the value of penelitian.id_tingkat_kesiapan_teknologi_target
     *
     * @mbg.generated
     */
    public Integer getIdTingkatKesiapanTeknologiTarget() {
        return idTingkatKesiapanTeknologiTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_tingkat_kesiapan_teknologi_target
     *
     * @param idTingkatKesiapanTeknologiTarget the value for penelitian.id_tingkat_kesiapan_teknologi_target
     *
     * @mbg.generated
     */
    public void setIdTingkatKesiapanTeknologiTarget(Integer idTingkatKesiapanTeknologiTarget) {
        this.idTingkatKesiapanTeknologiTarget = idTingkatKesiapanTeknologiTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.judul
     *
     * @return the value of penelitian.judul
     *
     * @mbg.generated
     */
    public String getJudul() {
        return judul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.judul
     *
     * @param judul the value for penelitian.judul
     *
     * @mbg.generated
     */
    public void setJudul(String judul) {
        this.judul = judul;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.ringkasan
     *
     * @return the value of penelitian.ringkasan
     *
     * @mbg.generated
     */
    public String getRingkasan() {
        return ringkasan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.ringkasan
     *
     * @param ringkasan the value for penelitian.ringkasan
     *
     * @mbg.generated
     */
    public void setRingkasan(String ringkasan) {
        this.ringkasan = ringkasan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.tahun_usulan
     *
     * @return the value of penelitian.tahun_usulan
     *
     * @mbg.generated
     */
    public String getTahunUsulan() {
        return tahunUsulan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.tahun_usulan
     *
     * @param tahunUsulan the value for penelitian.tahun_usulan
     *
     * @mbg.generated
     */
    public void setTahunUsulan(String tahunUsulan) {
        this.tahunUsulan = tahunUsulan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.tahun_mulai_pelaksanaan
     *
     * @return the value of penelitian.tahun_mulai_pelaksanaan
     *
     * @mbg.generated
     */
    public String getTahunMulaiPelaksanaan() {
        return tahunMulaiPelaksanaan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.tahun_mulai_pelaksanaan
     *
     * @param tahunMulaiPelaksanaan the value for penelitian.tahun_mulai_pelaksanaan
     *
     * @mbg.generated
     */
    public void setTahunMulaiPelaksanaan(String tahunMulaiPelaksanaan) {
        this.tahunMulaiPelaksanaan = tahunMulaiPelaksanaan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.tahun_selesai_pelaksanaan
     *
     * @return the value of penelitian.tahun_selesai_pelaksanaan
     *
     * @mbg.generated
     */
    public String getTahunSelesaiPelaksanaan() {
        return tahunSelesaiPelaksanaan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.tahun_selesai_pelaksanaan
     *
     * @param tahunSelesaiPelaksanaan the value for penelitian.tahun_selesai_pelaksanaan
     *
     * @mbg.generated
     */
    public void setTahunSelesaiPelaksanaan(String tahunSelesaiPelaksanaan) {
        this.tahunSelesaiPelaksanaan = tahunSelesaiPelaksanaan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.latar_belakang
     *
     * @return the value of penelitian.latar_belakang
     *
     * @mbg.generated
     */
    public String getLatarBelakang() {
        return latarBelakang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.latar_belakang
     *
     * @param latarBelakang the value for penelitian.latar_belakang
     *
     * @mbg.generated
     */
    public void setLatarBelakang(String latarBelakang) {
        this.latarBelakang = latarBelakang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.tinjauan_pustaka
     *
     * @return the value of penelitian.tinjauan_pustaka
     *
     * @mbg.generated
     */
    public String getTinjauanPustaka() {
        return tinjauanPustaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.tinjauan_pustaka
     *
     * @param tinjauanPustaka the value for penelitian.tinjauan_pustaka
     *
     * @mbg.generated
     */
    public void setTinjauanPustaka(String tinjauanPustaka) {
        this.tinjauanPustaka = tinjauanPustaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.metode
     *
     * @return the value of penelitian.metode
     *
     * @mbg.generated
     */
    public String getMetode() {
        return metode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.metode
     *
     * @param metode the value for penelitian.metode
     *
     * @mbg.generated
     */
    public void setMetode(String metode) {
        this.metode = metode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.daftar_pustaka
     *
     * @return the value of penelitian.daftar_pustaka
     *
     * @mbg.generated
     */
    public String getDaftarPustaka() {
        return daftarPustaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.daftar_pustaka
     *
     * @param daftarPustaka the value for penelitian.daftar_pustaka
     *
     * @mbg.generated
     */
    public void setDaftarPustaka(String daftarPustaka) {
        this.daftarPustaka = daftarPustaka;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_reviewer_skema
     *
     * @return the value of penelitian.id_reviewer_skema
     *
     * @mbg.generated
     */
    public Integer getIdReviewerSkema() {
        return idReviewerSkema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_reviewer_skema
     *
     * @param idReviewerSkema the value for penelitian.id_reviewer_skema
     *
     * @mbg.generated
     */
    public void setIdReviewerSkema(Integer idReviewerSkema) {
        this.idReviewerSkema = idReviewerSkema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.lokasi_penelitian
     *
     * @return the value of penelitian.lokasi_penelitian
     *
     * @mbg.generated
     */
    public String getLokasiPenelitian() {
        return lokasiPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.lokasi_penelitian
     *
     * @param lokasiPenelitian the value for penelitian.lokasi_penelitian
     *
     * @mbg.generated
     */
    public void setLokasiPenelitian(String lokasiPenelitian) {
        this.lokasiPenelitian = lokasiPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column penelitian.id_kelompok_tkt
     *
     * @return the value of penelitian.id_kelompok_tkt
     *
     * @mbg.generated
     */
    public Integer getIdKelompokTkt() {
        return idKelompokTkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column penelitian.id_kelompok_tkt
     *
     * @param idKelompokTkt the value for penelitian.id_kelompok_tkt
     *
     * @mbg.generated
     */
    public void setIdKelompokTkt(Integer idKelompokTkt) {
        this.idKelompokTkt = idKelompokTkt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penelitian
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Penelitian other = (Penelitian) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdTopik() == null ? other.getIdTopik() == null : this.getIdTopik().equals(other.getIdTopik()))
            && (this.getIdSkemaPenelitian() == null ? other.getIdSkemaPenelitian() == null : this.getIdSkemaPenelitian().equals(other.getIdSkemaPenelitian()))
            && (this.getIdRumpunIlmu() == null ? other.getIdRumpunIlmu() == null : this.getIdRumpunIlmu().equals(other.getIdRumpunIlmu()))
            && (this.getIdTingkatKesiapanTeknologi() == null ? other.getIdTingkatKesiapanTeknologi() == null : this.getIdTingkatKesiapanTeknologi().equals(other.getIdTingkatKesiapanTeknologi()))
            && (this.getIdTingkatKesiapanTeknologiTarget() == null ? other.getIdTingkatKesiapanTeknologiTarget() == null : this.getIdTingkatKesiapanTeknologiTarget().equals(other.getIdTingkatKesiapanTeknologiTarget()))
            && (this.getJudul() == null ? other.getJudul() == null : this.getJudul().equals(other.getJudul()))
            && (this.getRingkasan() == null ? other.getRingkasan() == null : this.getRingkasan().equals(other.getRingkasan()))
            && (this.getTahunUsulan() == null ? other.getTahunUsulan() == null : this.getTahunUsulan().equals(other.getTahunUsulan()))
            && (this.getTahunMulaiPelaksanaan() == null ? other.getTahunMulaiPelaksanaan() == null : this.getTahunMulaiPelaksanaan().equals(other.getTahunMulaiPelaksanaan()))
            && (this.getTahunSelesaiPelaksanaan() == null ? other.getTahunSelesaiPelaksanaan() == null : this.getTahunSelesaiPelaksanaan().equals(other.getTahunSelesaiPelaksanaan()))
            && (this.getLatarBelakang() == null ? other.getLatarBelakang() == null : this.getLatarBelakang().equals(other.getLatarBelakang()))
            && (this.getTinjauanPustaka() == null ? other.getTinjauanPustaka() == null : this.getTinjauanPustaka().equals(other.getTinjauanPustaka()))
            && (this.getMetode() == null ? other.getMetode() == null : this.getMetode().equals(other.getMetode()))
            && (this.getDaftarPustaka() == null ? other.getDaftarPustaka() == null : this.getDaftarPustaka().equals(other.getDaftarPustaka()))
            && (this.getIdReviewerSkema() == null ? other.getIdReviewerSkema() == null : this.getIdReviewerSkema().equals(other.getIdReviewerSkema()))
            && (this.getLokasiPenelitian() == null ? other.getLokasiPenelitian() == null : this.getLokasiPenelitian().equals(other.getLokasiPenelitian()))
            && (this.getIdKelompokTkt() == null ? other.getIdKelompokTkt() == null : this.getIdKelompokTkt().equals(other.getIdKelompokTkt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table penelitian
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdTopik() == null) ? 0 : getIdTopik().hashCode());
        result = prime * result + ((getIdSkemaPenelitian() == null) ? 0 : getIdSkemaPenelitian().hashCode());
        result = prime * result + ((getIdRumpunIlmu() == null) ? 0 : getIdRumpunIlmu().hashCode());
        result = prime * result + ((getIdTingkatKesiapanTeknologi() == null) ? 0 : getIdTingkatKesiapanTeknologi().hashCode());
        result = prime * result + ((getIdTingkatKesiapanTeknologiTarget() == null) ? 0 : getIdTingkatKesiapanTeknologiTarget().hashCode());
        result = prime * result + ((getJudul() == null) ? 0 : getJudul().hashCode());
        result = prime * result + ((getRingkasan() == null) ? 0 : getRingkasan().hashCode());
        result = prime * result + ((getTahunUsulan() == null) ? 0 : getTahunUsulan().hashCode());
        result = prime * result + ((getTahunMulaiPelaksanaan() == null) ? 0 : getTahunMulaiPelaksanaan().hashCode());
        result = prime * result + ((getTahunSelesaiPelaksanaan() == null) ? 0 : getTahunSelesaiPelaksanaan().hashCode());
        result = prime * result + ((getLatarBelakang() == null) ? 0 : getLatarBelakang().hashCode());
        result = prime * result + ((getTinjauanPustaka() == null) ? 0 : getTinjauanPustaka().hashCode());
        result = prime * result + ((getMetode() == null) ? 0 : getMetode().hashCode());
        result = prime * result + ((getDaftarPustaka() == null) ? 0 : getDaftarPustaka().hashCode());
        result = prime * result + ((getIdReviewerSkema() == null) ? 0 : getIdReviewerSkema().hashCode());
        result = prime * result + ((getLokasiPenelitian() == null) ? 0 : getLokasiPenelitian().hashCode());
        result = prime * result + ((getIdKelompokTkt() == null) ? 0 : getIdKelompokTkt().hashCode());
        return result;
    }
}