package com.pusilkom.base.model;

import java.io.Serializable;

public class RoleHasMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_menu.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_menu.id_role
     *
     * @mbg.generated
     */
    private Long idRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_has_menu.id_menu
     *
     * @mbg.generated
     */
    private Long idMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_has_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_menu.id
     *
     * @return the value of role_has_menu.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_menu.id
     *
     * @param id the value for role_has_menu.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_menu.id_role
     *
     * @return the value of role_has_menu.id_role
     *
     * @mbg.generated
     */
    public Long getIdRole() {
        return idRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_menu.id_role
     *
     * @param idRole the value for role_has_menu.id_role
     *
     * @mbg.generated
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_has_menu.id_menu
     *
     * @return the value of role_has_menu.id_menu
     *
     * @mbg.generated
     */
    public Long getIdMenu() {
        return idMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_has_menu.id_menu
     *
     * @param idMenu the value for role_has_menu.id_menu
     *
     * @mbg.generated
     */
    public void setIdMenu(Long idMenu) {
        this.idMenu = idMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_menu
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleHasMenu other = (RoleHasMenu) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdRole() == null ? other.getIdRole() == null : this.getIdRole().equals(other.getIdRole()))
            && (this.getIdMenu() == null ? other.getIdMenu() == null : this.getIdMenu().equals(other.getIdMenu()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_has_menu
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdRole() == null) ? 0 : getIdRole().hashCode());
        result = prime * result + ((getIdMenu() == null) ? 0 : getIdMenu().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "RoleHasMenu{" +
                "id=" + id +
                ", idRole=" + idRole +
                ", idMenu=" + idMenu +
                '}';
    }
}