package com.pusilkom.base.model;

import java.io.Serializable;

public class StatusTahapPenelitian implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.id_status_syarat_1
     *
     * @mbg.generated
     */
    private Integer idStatusSyarat1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.id_tahap_penelitian
     *
     * @mbg.generated
     */
    private Integer idTahapPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.id_status_syarat_2
     *
     * @mbg.generated
     */
    private Integer idStatusSyarat2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.kode_status
     *
     * @mbg.generated
     */
    private String kodeStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.kode_role_1
     *
     * @mbg.generated
     */
    private String kodeRole1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.kode_role_2
     *
     * @mbg.generated
     */
    private String kodeRole2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column status_tahap_penelitian.label_button
     *
     * @mbg.generated
     */
    private String labelButton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table status_tahap_penelitian
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.id
     *
     * @return the value of status_tahap_penelitian.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.id
     *
     * @param id the value for status_tahap_penelitian.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.id_status_syarat_1
     *
     * @return the value of status_tahap_penelitian.id_status_syarat_1
     *
     * @mbg.generated
     */
    public Integer getIdStatusSyarat1() {
        return idStatusSyarat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.id_status_syarat_1
     *
     * @param idStatusSyarat1 the value for status_tahap_penelitian.id_status_syarat_1
     *
     * @mbg.generated
     */
    public void setIdStatusSyarat1(Integer idStatusSyarat1) {
        this.idStatusSyarat1 = idStatusSyarat1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.id_tahap_penelitian
     *
     * @return the value of status_tahap_penelitian.id_tahap_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdTahapPenelitian() {
        return idTahapPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.id_tahap_penelitian
     *
     * @param idTahapPenelitian the value for status_tahap_penelitian.id_tahap_penelitian
     *
     * @mbg.generated
     */
    public void setIdTahapPenelitian(Integer idTahapPenelitian) {
        this.idTahapPenelitian = idTahapPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.nama
     *
     * @return the value of status_tahap_penelitian.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.nama
     *
     * @param nama the value for status_tahap_penelitian.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.id_status_syarat_2
     *
     * @return the value of status_tahap_penelitian.id_status_syarat_2
     *
     * @mbg.generated
     */
    public Integer getIdStatusSyarat2() {
        return idStatusSyarat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.id_status_syarat_2
     *
     * @param idStatusSyarat2 the value for status_tahap_penelitian.id_status_syarat_2
     *
     * @mbg.generated
     */
    public void setIdStatusSyarat2(Integer idStatusSyarat2) {
        this.idStatusSyarat2 = idStatusSyarat2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.kode_status
     *
     * @return the value of status_tahap_penelitian.kode_status
     *
     * @mbg.generated
     */
    public String getKodeStatus() {
        return kodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.kode_status
     *
     * @param kodeStatus the value for status_tahap_penelitian.kode_status
     *
     * @mbg.generated
     */
    public void setKodeStatus(String kodeStatus) {
        this.kodeStatus = kodeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.kode_role_1
     *
     * @return the value of status_tahap_penelitian.kode_role_1
     *
     * @mbg.generated
     */
    public String getKodeRole1() {
        return kodeRole1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.kode_role_1
     *
     * @param kodeRole1 the value for status_tahap_penelitian.kode_role_1
     *
     * @mbg.generated
     */
    public void setKodeRole1(String kodeRole1) {
        this.kodeRole1 = kodeRole1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.kode_role_2
     *
     * @return the value of status_tahap_penelitian.kode_role_2
     *
     * @mbg.generated
     */
    public String getKodeRole2() {
        return kodeRole2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.kode_role_2
     *
     * @param kodeRole2 the value for status_tahap_penelitian.kode_role_2
     *
     * @mbg.generated
     */
    public void setKodeRole2(String kodeRole2) {
        this.kodeRole2 = kodeRole2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column status_tahap_penelitian.label_button
     *
     * @return the value of status_tahap_penelitian.label_button
     *
     * @mbg.generated
     */
    public String getLabelButton() {
        return labelButton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column status_tahap_penelitian.label_button
     *
     * @param labelButton the value for status_tahap_penelitian.label_button
     *
     * @mbg.generated
     */
    public void setLabelButton(String labelButton) {
        this.labelButton = labelButton;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_tahap_penelitian
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        StatusTahapPenelitian other = (StatusTahapPenelitian) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdStatusSyarat1() == null ? other.getIdStatusSyarat1() == null : this.getIdStatusSyarat1().equals(other.getIdStatusSyarat1()))
            && (this.getIdTahapPenelitian() == null ? other.getIdTahapPenelitian() == null : this.getIdTahapPenelitian().equals(other.getIdTahapPenelitian()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getIdStatusSyarat2() == null ? other.getIdStatusSyarat2() == null : this.getIdStatusSyarat2().equals(other.getIdStatusSyarat2()))
            && (this.getKodeStatus() == null ? other.getKodeStatus() == null : this.getKodeStatus().equals(other.getKodeStatus()))
            && (this.getKodeRole1() == null ? other.getKodeRole1() == null : this.getKodeRole1().equals(other.getKodeRole1()))
            && (this.getKodeRole2() == null ? other.getKodeRole2() == null : this.getKodeRole2().equals(other.getKodeRole2()))
            && (this.getLabelButton() == null ? other.getLabelButton() == null : this.getLabelButton().equals(other.getLabelButton()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table status_tahap_penelitian
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdStatusSyarat1() == null) ? 0 : getIdStatusSyarat1().hashCode());
        result = prime * result + ((getIdTahapPenelitian() == null) ? 0 : getIdTahapPenelitian().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getIdStatusSyarat2() == null) ? 0 : getIdStatusSyarat2().hashCode());
        result = prime * result + ((getKodeStatus() == null) ? 0 : getKodeStatus().hashCode());
        result = prime * result + ((getKodeRole1() == null) ? 0 : getKodeRole1().hashCode());
        result = prime * result + ((getKodeRole2() == null) ? 0 : getKodeRole2().hashCode());
        result = prime * result + ((getLabelButton() == null) ? 0 : getLabelButton().hashCode());
        return result;
    }
}