package com.pusilkom.base.model;

import java.io.Serializable;

public class TargetOutputPenelitian implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.id_penelitian
     *
     * @mbg.generated
     */
    private Integer idPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.tahun_target
     *
     * @mbg.generated
     */
    private String tahunTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.tahun_realisasi
     *
     * @mbg.generated
     */
    private String tahunRealisasi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.is_wajib
     *
     * @mbg.generated
     */
    private Boolean isWajib;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.is_tambahan
     *
     * @mbg.generated
     */
    private Boolean isTambahan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column target_output_penelitian.id_jenis_output
     *
     * @mbg.generated
     */
    private Integer idJenisOutput;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table target_output_penelitian
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.id
     *
     * @return the value of target_output_penelitian.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.id
     *
     * @param id the value for target_output_penelitian.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.id_penelitian
     *
     * @return the value of target_output_penelitian.id_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdPenelitian() {
        return idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.id_penelitian
     *
     * @param idPenelitian the value for target_output_penelitian.id_penelitian
     *
     * @mbg.generated
     */
    public void setIdPenelitian(Integer idPenelitian) {
        this.idPenelitian = idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.tahun_target
     *
     * @return the value of target_output_penelitian.tahun_target
     *
     * @mbg.generated
     */
    public String getTahunTarget() {
        return tahunTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.tahun_target
     *
     * @param tahunTarget the value for target_output_penelitian.tahun_target
     *
     * @mbg.generated
     */
    public void setTahunTarget(String tahunTarget) {
        this.tahunTarget = tahunTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.tahun_realisasi
     *
     * @return the value of target_output_penelitian.tahun_realisasi
     *
     * @mbg.generated
     */
    public String getTahunRealisasi() {
        return tahunRealisasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.tahun_realisasi
     *
     * @param tahunRealisasi the value for target_output_penelitian.tahun_realisasi
     *
     * @mbg.generated
     */
    public void setTahunRealisasi(String tahunRealisasi) {
        this.tahunRealisasi = tahunRealisasi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.is_wajib
     *
     * @return the value of target_output_penelitian.is_wajib
     *
     * @mbg.generated
     */
    public Boolean getIsWajib() {
        return isWajib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.is_wajib
     *
     * @param isWajib the value for target_output_penelitian.is_wajib
     *
     * @mbg.generated
     */
    public void setIsWajib(Boolean isWajib) {
        this.isWajib = isWajib;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.is_tambahan
     *
     * @return the value of target_output_penelitian.is_tambahan
     *
     * @mbg.generated
     */
    public Boolean getIsTambahan() {
        return isTambahan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.is_tambahan
     *
     * @param isTambahan the value for target_output_penelitian.is_tambahan
     *
     * @mbg.generated
     */
    public void setIsTambahan(Boolean isTambahan) {
        this.isTambahan = isTambahan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column target_output_penelitian.id_jenis_output
     *
     * @return the value of target_output_penelitian.id_jenis_output
     *
     * @mbg.generated
     */
    public Integer getIdJenisOutput() {
        return idJenisOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column target_output_penelitian.id_jenis_output
     *
     * @param idJenisOutput the value for target_output_penelitian.id_jenis_output
     *
     * @mbg.generated
     */
    public void setIdJenisOutput(Integer idJenisOutput) {
        this.idJenisOutput = idJenisOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_output_penelitian
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TargetOutputPenelitian other = (TargetOutputPenelitian) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdPenelitian() == null ? other.getIdPenelitian() == null : this.getIdPenelitian().equals(other.getIdPenelitian()))
            && (this.getTahunTarget() == null ? other.getTahunTarget() == null : this.getTahunTarget().equals(other.getTahunTarget()))
            && (this.getTahunRealisasi() == null ? other.getTahunRealisasi() == null : this.getTahunRealisasi().equals(other.getTahunRealisasi()))
            && (this.getIsWajib() == null ? other.getIsWajib() == null : this.getIsWajib().equals(other.getIsWajib()))
            && (this.getIsTambahan() == null ? other.getIsTambahan() == null : this.getIsTambahan().equals(other.getIsTambahan()))
            && (this.getIdJenisOutput() == null ? other.getIdJenisOutput() == null : this.getIdJenisOutput().equals(other.getIdJenisOutput()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table target_output_penelitian
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdPenelitian() == null) ? 0 : getIdPenelitian().hashCode());
        result = prime * result + ((getTahunTarget() == null) ? 0 : getTahunTarget().hashCode());
        result = prime * result + ((getTahunRealisasi() == null) ? 0 : getTahunRealisasi().hashCode());
        result = prime * result + ((getIsWajib() == null) ? 0 : getIsWajib().hashCode());
        result = prime * result + ((getIsTambahan() == null) ? 0 : getIsTambahan().hashCode());
        result = prime * result + ((getIdJenisOutput() == null) ? 0 : getIdJenisOutput().hashCode());
        return result;
    }
}