package com.pusilkom.base.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TimPenelitiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public TimPenelitiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiIsNull() {
            addCriterion("id_peneliti is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiIsNotNull() {
            addCriterion("id_peneliti is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiEqualTo(Integer value) {
            addCriterion("id_peneliti =", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiNotEqualTo(Integer value) {
            addCriterion("id_peneliti <>", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiGreaterThan(Integer value) {
            addCriterion("id_peneliti >", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_peneliti >=", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiLessThan(Integer value) {
            addCriterion("id_peneliti <", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiLessThanOrEqualTo(Integer value) {
            addCriterion("id_peneliti <=", value, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiIn(List<Integer> values) {
            addCriterion("id_peneliti in", values, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiNotIn(List<Integer> values) {
            addCriterion("id_peneliti not in", values, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiBetween(Integer value1, Integer value2) {
            addCriterion("id_peneliti between", value1, value2, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_peneliti not between", value1, value2, "idPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNull() {
            addCriterion("id_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNotNull() {
            addCriterion("id_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianEqualTo(Integer value) {
            addCriterion("id_penelitian =", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotEqualTo(Integer value) {
            addCriterion("id_penelitian <>", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThan(Integer value) {
            addCriterion("id_penelitian >", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian >=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThan(Integer value) {
            addCriterion("id_penelitian <", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian <=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIn(List<Integer> values) {
            addCriterion("id_penelitian in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotIn(List<Integer> values) {
            addCriterion("id_penelitian not in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian not between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiIsNull() {
            addCriterion("id_peran_peneliti is null");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiIsNotNull() {
            addCriterion("id_peran_peneliti is not null");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiEqualTo(Integer value) {
            addCriterion("id_peran_peneliti =", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiNotEqualTo(Integer value) {
            addCriterion("id_peran_peneliti <>", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiGreaterThan(Integer value) {
            addCriterion("id_peran_peneliti >", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_peran_peneliti >=", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiLessThan(Integer value) {
            addCriterion("id_peran_peneliti <", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiLessThanOrEqualTo(Integer value) {
            addCriterion("id_peran_peneliti <=", value, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiIn(List<Integer> values) {
            addCriterion("id_peran_peneliti in", values, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiNotIn(List<Integer> values) {
            addCriterion("id_peran_peneliti not in", values, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiBetween(Integer value1, Integer value2) {
            addCriterion("id_peran_peneliti between", value1, value2, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdPeranPenelitiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_peran_peneliti not between", value1, value2, "idPeranPeneliti");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIsNull() {
            addCriterion("id_organisasi is null");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIsNotNull() {
            addCriterion("id_organisasi is not null");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiEqualTo(Integer value) {
            addCriterion("id_organisasi =", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotEqualTo(Integer value) {
            addCriterion("id_organisasi <>", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiGreaterThan(Integer value) {
            addCriterion("id_organisasi >", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_organisasi >=", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiLessThan(Integer value) {
            addCriterion("id_organisasi <", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiLessThanOrEqualTo(Integer value) {
            addCriterion("id_organisasi <=", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIn(List<Integer> values) {
            addCriterion("id_organisasi in", values, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotIn(List<Integer> values) {
            addCriterion("id_organisasi not in", values, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiBetween(Integer value1, Integer value2) {
            addCriterion("id_organisasi between", value1, value2, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_organisasi not between", value1, value2, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniIsNull() {
            addCriterion("id_bidang_keahlian_saat_ini is null");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniIsNotNull() {
            addCriterion("id_bidang_keahlian_saat_ini is not null");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniEqualTo(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini =", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniNotEqualTo(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini <>", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniGreaterThan(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini >", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini >=", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniLessThan(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini <", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniLessThanOrEqualTo(Integer value) {
            addCriterion("id_bidang_keahlian_saat_ini <=", value, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniIn(List<Integer> values) {
            addCriterion("id_bidang_keahlian_saat_ini in", values, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniNotIn(List<Integer> values) {
            addCriterion("id_bidang_keahlian_saat_ini not in", values, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniBetween(Integer value1, Integer value2) {
            addCriterion("id_bidang_keahlian_saat_ini between", value1, value2, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andIdBidangKeahlianSaatIniNotBetween(Integer value1, Integer value2) {
            addCriterion("id_bidang_keahlian_saat_ini not between", value1, value2, "idBidangKeahlianSaatIni");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianIsNull() {
            addCriterion("tugas_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianIsNotNull() {
            addCriterion("tugas_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianEqualTo(String value) {
            addCriterion("tugas_penelitian =", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianNotEqualTo(String value) {
            addCriterion("tugas_penelitian <>", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianGreaterThan(String value) {
            addCriterion("tugas_penelitian >", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianGreaterThanOrEqualTo(String value) {
            addCriterion("tugas_penelitian >=", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianLessThan(String value) {
            addCriterion("tugas_penelitian <", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianLessThanOrEqualTo(String value) {
            addCriterion("tugas_penelitian <=", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianLike(String value) {
            addCriterion("tugas_penelitian like", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianNotLike(String value) {
            addCriterion("tugas_penelitian not like", value, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianIn(List<String> values) {
            addCriterion("tugas_penelitian in", values, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianNotIn(List<String> values) {
            addCriterion("tugas_penelitian not in", values, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianBetween(String value1, String value2) {
            addCriterion("tugas_penelitian between", value1, value2, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianNotBetween(String value1, String value2) {
            addCriterion("tugas_penelitian not between", value1, value2, "tugasPenelitian");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguIsNull() {
            addCriterion("alokasi_jam_per_minggu is null");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguIsNotNull() {
            addCriterion("alokasi_jam_per_minggu is not null");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguEqualTo(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu =", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguNotEqualTo(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu <>", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguGreaterThan(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu >", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu >=", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguLessThan(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu <", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguLessThanOrEqualTo(BigDecimal value) {
            addCriterion("alokasi_jam_per_minggu <=", value, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguIn(List<BigDecimal> values) {
            addCriterion("alokasi_jam_per_minggu in", values, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguNotIn(List<BigDecimal> values) {
            addCriterion("alokasi_jam_per_minggu not in", values, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alokasi_jam_per_minggu between", value1, value2, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andAlokasiJamPerMingguNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("alokasi_jam_per_minggu not between", value1, value2, "alokasiJamPerMinggu");
            return (Criteria) this;
        }

        public Criteria andTugasPenelitianLikeInsensitive(String value) {
            addCriterion("upper(tugas_penelitian) like", value.toUpperCase(), "tugasPenelitian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tim_peneliti
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tim_peneliti
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}