---
.base-build:
  image: maven:3.6.3-adoptopenjdk-11
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - .m2/repository
    policy: pull-push
  variables:
    # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
    # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
    MAVEN_OPTS: >-
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true"
    # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
    # when running from the command line.
    # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version

resolve:
  extends: .base-build
  stage: dependencies
  cache:
    policy: push
  script:
    - mvn ${MAVEN_CLI_OPTS} clean dependency:resolve dependency:resolve-plugins
  only:
    changes:
      - pom.xml

verify:
  extends: .base-build
  stage: build
  cache:
    policy: pull-push
  script:
    - mvn ${MAVEN_CLI_OPTS} clean verify
  artifacts:
    paths:
      - target/
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
  except:
    - schedules

sonarscan:
  extends: .base-build
  stage: static-analysis
  cache:
    policy: pull
  script:
    - mvn ${MAVEN_CLI_OPTS} sonar:sonar
      -Dsonar.projectKey=com.pusilkom:ppsdm-simlitekkes-backend
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.token=${SONAR_TOKEN}
      -Dsonar.branch.name=${CI_COMMIT_REF_NAME}
  only:
    - develop@ppsdm/simlitekkes-backend
    - testing@ppsdm/simlitekkes-backend
    - master@ppsdm/simlitekkes-backend
  except:
    - schedules
