---
version: "3"
services:
  backend:
    image: registry.pusilkom.com/ppsdm/simlitekkes-backend:latest
    depends_on: 
      - db
    expose:
      - "8001"
    restart: always
    volumes:
      - backend-data:/app/file
  db:
    image: postgres:12-alpine
    expose:
      - "5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  backend-data:
  db-data: