---
version: "3"
services:
  adminer:
    image: adminer:4.7
    environment:
      ADMINER_DESIGN: mancave
    depends_on:
      - db
    ports:
      - "8080"
  backend:
    image: registry.pusilkom.com/ppsdm/simlitekkes-backend:localhost
    build:
      context: ../..
      dockerfile: Dockerfile
    env_file:
      - .env-local
    ports:
      - "8001"
  db:
    env_file:
      - .env-local
    command: postgres -c 'max_connections=200'
    ports:
      - "5432"
    volumes:
      - "../../initial_script.sql:/docker-entrypoint-initdb.d/000_init.sql:ro"
