package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BeritaExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table berita
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table berita
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table berita
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public BeritaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berita
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table berita
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIsNull() {
            addCriterion("id_organisasi is null");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIsNotNull() {
            addCriterion("id_organisasi is not null");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiEqualTo(Integer value) {
            addCriterion("id_organisasi =", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotEqualTo(Integer value) {
            addCriterion("id_organisasi <>", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiGreaterThan(Integer value) {
            addCriterion("id_organisasi >", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_organisasi >=", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiLessThan(Integer value) {
            addCriterion("id_organisasi <", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiLessThanOrEqualTo(Integer value) {
            addCriterion("id_organisasi <=", value, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiIn(List<Integer> values) {
            addCriterion("id_organisasi in", values, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotIn(List<Integer> values) {
            addCriterion("id_organisasi not in", values, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiBetween(Integer value1, Integer value2) {
            addCriterion("id_organisasi between", value1, value2, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andIdOrganisasiNotBetween(Integer value1, Integer value2) {
            addCriterion("id_organisasi not between", value1, value2, "idOrganisasi");
            return (Criteria) this;
        }

        public Criteria andJudulIsNull() {
            addCriterion("judul is null");
            return (Criteria) this;
        }

        public Criteria andJudulIsNotNull() {
            addCriterion("judul is not null");
            return (Criteria) this;
        }

        public Criteria andJudulEqualTo(String value) {
            addCriterion("judul =", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotEqualTo(String value) {
            addCriterion("judul <>", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulGreaterThan(String value) {
            addCriterion("judul >", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulGreaterThanOrEqualTo(String value) {
            addCriterion("judul >=", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLessThan(String value) {
            addCriterion("judul <", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLessThanOrEqualTo(String value) {
            addCriterion("judul <=", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLike(String value) {
            addCriterion("judul like", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotLike(String value) {
            addCriterion("judul not like", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulIn(List<String> values) {
            addCriterion("judul in", values, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotIn(List<String> values) {
            addCriterion("judul not in", values, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulBetween(String value1, String value2) {
            addCriterion("judul between", value1, value2, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotBetween(String value1, String value2) {
            addCriterion("judul not between", value1, value2, "judul");
            return (Criteria) this;
        }

        public Criteria andIsiIsNull() {
            addCriterion("isi is null");
            return (Criteria) this;
        }

        public Criteria andIsiIsNotNull() {
            addCriterion("isi is not null");
            return (Criteria) this;
        }

        public Criteria andIsiEqualTo(String value) {
            addCriterion("isi =", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiNotEqualTo(String value) {
            addCriterion("isi <>", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiGreaterThan(String value) {
            addCriterion("isi >", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiGreaterThanOrEqualTo(String value) {
            addCriterion("isi >=", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiLessThan(String value) {
            addCriterion("isi <", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiLessThanOrEqualTo(String value) {
            addCriterion("isi <=", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiLike(String value) {
            addCriterion("isi like", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiNotLike(String value) {
            addCriterion("isi not like", value, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiIn(List<String> values) {
            addCriterion("isi in", values, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiNotIn(List<String> values) {
            addCriterion("isi not in", values, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiBetween(String value1, String value2) {
            addCriterion("isi between", value1, value2, "isi");
            return (Criteria) this;
        }

        public Criteria andIsiNotBetween(String value1, String value2) {
            addCriterion("isi not between", value1, value2, "isi");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNull() {
            addCriterion("is_published is null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIsNotNull() {
            addCriterion("is_published is not null");
            return (Criteria) this;
        }

        public Criteria andIsPublishedEqualTo(Boolean value) {
            addCriterion("is_published =", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotEqualTo(Boolean value) {
            addCriterion("is_published <>", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThan(Boolean value) {
            addCriterion("is_published >", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_published >=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThan(Boolean value) {
            addCriterion("is_published <", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_published <=", value, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedIn(List<Boolean> values) {
            addCriterion("is_published in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotIn(List<Boolean> values) {
            addCriterion("is_published not in", values, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andIsPublishedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_published not between", value1, value2, "isPublished");
            return (Criteria) this;
        }

        public Criteria andUserPublishIsNull() {
            addCriterion("user_publish is null");
            return (Criteria) this;
        }

        public Criteria andUserPublishIsNotNull() {
            addCriterion("user_publish is not null");
            return (Criteria) this;
        }

        public Criteria andUserPublishEqualTo(String value) {
            addCriterion("user_publish =", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishNotEqualTo(String value) {
            addCriterion("user_publish <>", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishGreaterThan(String value) {
            addCriterion("user_publish >", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishGreaterThanOrEqualTo(String value) {
            addCriterion("user_publish >=", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishLessThan(String value) {
            addCriterion("user_publish <", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishLessThanOrEqualTo(String value) {
            addCriterion("user_publish <=", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishLike(String value) {
            addCriterion("user_publish like", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishNotLike(String value) {
            addCriterion("user_publish not like", value, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishIn(List<String> values) {
            addCriterion("user_publish in", values, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishNotIn(List<String> values) {
            addCriterion("user_publish not in", values, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishBetween(String value1, String value2) {
            addCriterion("user_publish between", value1, value2, "userPublish");
            return (Criteria) this;
        }

        public Criteria andUserPublishNotBetween(String value1, String value2) {
            addCriterion("user_publish not between", value1, value2, "userPublish");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampIsNull() {
            addCriterion("publish_timestamp is null");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampIsNotNull() {
            addCriterion("publish_timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampEqualTo(Date value) {
            addCriterion("publish_timestamp =", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampNotEqualTo(Date value) {
            addCriterion("publish_timestamp <>", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampGreaterThan(Date value) {
            addCriterion("publish_timestamp >", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("publish_timestamp >=", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampLessThan(Date value) {
            addCriterion("publish_timestamp <", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampLessThanOrEqualTo(Date value) {
            addCriterion("publish_timestamp <=", value, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampIn(List<Date> values) {
            addCriterion("publish_timestamp in", values, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampNotIn(List<Date> values) {
            addCriterion("publish_timestamp not in", values, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampBetween(Date value1, Date value2) {
            addCriterion("publish_timestamp between", value1, value2, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andPublishTimestampNotBetween(Date value1, Date value2) {
            addCriterion("publish_timestamp not between", value1, value2, "publishTimestamp");
            return (Criteria) this;
        }

        public Criteria andJudulLikeInsensitive(String value) {
            addCriterion("upper(judul) like", value.toUpperCase(), "judul");
            return (Criteria) this;
        }

        public Criteria andIsiLikeInsensitive(String value) {
            addCriterion("upper(isi) like", value.toUpperCase(), "isi");
            return (Criteria) this;
        }

        public Criteria andUserPublishLikeInsensitive(String value) {
            addCriterion("upper(user_publish) like", value.toUpperCase(), "userPublish");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table berita
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table berita
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}