package com.pusilkom.base.model;

import java.io.Serializable;

public class Buku implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buku.id_output
     *
     * @mbg.generated
     */
    private Integer idOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buku.nama_penerbit
     *
     * @mbg.generated
     */
    private String namaPenerbit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buku.tahun_terbit
     *
     * @mbg.generated
     */
    private String tahunTerbit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buku.isbn
     *
     * @mbg.generated
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buku.jumlah_halaman
     *
     * @mbg.generated
     */
    private Integer jumlahHalaman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buku
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buku.id_output
     *
     * @return the value of buku.id_output
     *
     * @mbg.generated
     */
    public Integer getIdOutput() {
        return idOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buku.id_output
     *
     * @param idOutput the value for buku.id_output
     *
     * @mbg.generated
     */
    public void setIdOutput(Integer idOutput) {
        this.idOutput = idOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buku.nama_penerbit
     *
     * @return the value of buku.nama_penerbit
     *
     * @mbg.generated
     */
    public String getNamaPenerbit() {
        return namaPenerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buku.nama_penerbit
     *
     * @param namaPenerbit the value for buku.nama_penerbit
     *
     * @mbg.generated
     */
    public void setNamaPenerbit(String namaPenerbit) {
        this.namaPenerbit = namaPenerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buku.tahun_terbit
     *
     * @return the value of buku.tahun_terbit
     *
     * @mbg.generated
     */
    public String getTahunTerbit() {
        return tahunTerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buku.tahun_terbit
     *
     * @param tahunTerbit the value for buku.tahun_terbit
     *
     * @mbg.generated
     */
    public void setTahunTerbit(String tahunTerbit) {
        this.tahunTerbit = tahunTerbit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buku.isbn
     *
     * @return the value of buku.isbn
     *
     * @mbg.generated
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buku.isbn
     *
     * @param isbn the value for buku.isbn
     *
     * @mbg.generated
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buku.jumlah_halaman
     *
     * @return the value of buku.jumlah_halaman
     *
     * @mbg.generated
     */
    public Integer getJumlahHalaman() {
        return jumlahHalaman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buku.jumlah_halaman
     *
     * @param jumlahHalaman the value for buku.jumlah_halaman
     *
     * @mbg.generated
     */
    public void setJumlahHalaman(Integer jumlahHalaman) {
        this.jumlahHalaman = jumlahHalaman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buku
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Buku other = (Buku) that;
        return (this.getIdOutput() == null ? other.getIdOutput() == null : this.getIdOutput().equals(other.getIdOutput()))
            && (this.getNamaPenerbit() == null ? other.getNamaPenerbit() == null : this.getNamaPenerbit().equals(other.getNamaPenerbit()))
            && (this.getTahunTerbit() == null ? other.getTahunTerbit() == null : this.getTahunTerbit().equals(other.getTahunTerbit()))
            && (this.getIsbn() == null ? other.getIsbn() == null : this.getIsbn().equals(other.getIsbn()))
            && (this.getJumlahHalaman() == null ? other.getJumlahHalaman() == null : this.getJumlahHalaman().equals(other.getJumlahHalaman()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buku
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdOutput() == null) ? 0 : getIdOutput().hashCode());
        result = prime * result + ((getNamaPenerbit() == null) ? 0 : getNamaPenerbit().hashCode());
        result = prime * result + ((getTahunTerbit() == null) ? 0 : getTahunTerbit().hashCode());
        result = prime * result + ((getIsbn() == null) ? 0 : getIsbn().hashCode());
        result = prime * result + ((getJumlahHalaman() == null) ? 0 : getJumlahHalaman().hashCode());
        return result;
    }
}