package com.pusilkom.base.model;

import java.io.Serializable;

public class IndikatorTkt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indikator_tkt.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indikator_tkt.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    private Integer idTingkatKesiapanTeknologi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indikator_tkt.deskripsi
     *
     * @mbg.generated
     */
    private String deskripsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table indikator_tkt
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indikator_tkt.id
     *
     * @return the value of indikator_tkt.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indikator_tkt.id
     *
     * @param id the value for indikator_tkt.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indikator_tkt.id_tingkat_kesiapan_teknologi
     *
     * @return the value of indikator_tkt.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    public Integer getIdTingkatKesiapanTeknologi() {
        return idTingkatKesiapanTeknologi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indikator_tkt.id_tingkat_kesiapan_teknologi
     *
     * @param idTingkatKesiapanTeknologi the value for indikator_tkt.id_tingkat_kesiapan_teknologi
     *
     * @mbg.generated
     */
    public void setIdTingkatKesiapanTeknologi(Integer idTingkatKesiapanTeknologi) {
        this.idTingkatKesiapanTeknologi = idTingkatKesiapanTeknologi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indikator_tkt.deskripsi
     *
     * @return the value of indikator_tkt.deskripsi
     *
     * @mbg.generated
     */
    public String getDeskripsi() {
        return deskripsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indikator_tkt.deskripsi
     *
     * @param deskripsi the value for indikator_tkt.deskripsi
     *
     * @mbg.generated
     */
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indikator_tkt
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IndikatorTkt other = (IndikatorTkt) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdTingkatKesiapanTeknologi() == null ? other.getIdTingkatKesiapanTeknologi() == null : this.getIdTingkatKesiapanTeknologi().equals(other.getIdTingkatKesiapanTeknologi()))
            && (this.getDeskripsi() == null ? other.getDeskripsi() == null : this.getDeskripsi().equals(other.getDeskripsi()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indikator_tkt
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdTingkatKesiapanTeknologi() == null) ? 0 : getIdTingkatKesiapanTeknologi().hashCode());
        result = prime * result + ((getDeskripsi() == null) ? 0 : getDeskripsi().hashCode());
        return result;
    }
}