package com.pusilkom.base.model;

import java.io.Serializable;
import java.util.Date;

public class JadwalKegiatan implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.id_penelitian
     *
     * @mbg.generated
     */
    private Integer idPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.tanggal_awal_jadwal
     *
     * @mbg.generated
     */
    private Date tanggalAwalJadwal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.tanggal_akhir_jadwal
     *
     * @mbg.generated
     */
    private Date tanggalAkhirJadwal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.tahun
     *
     * @mbg.generated
     */
    private Short tahun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jadwal_kegiatan.nama_kegiatan
     *
     * @mbg.generated
     */
    private String namaKegiatan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jadwal_kegiatan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.id
     *
     * @return the value of jadwal_kegiatan.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.id
     *
     * @param id the value for jadwal_kegiatan.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.id_penelitian
     *
     * @return the value of jadwal_kegiatan.id_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdPenelitian() {
        return idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.id_penelitian
     *
     * @param idPenelitian the value for jadwal_kegiatan.id_penelitian
     *
     * @mbg.generated
     */
    public void setIdPenelitian(Integer idPenelitian) {
        this.idPenelitian = idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.tanggal_awal_jadwal
     *
     * @return the value of jadwal_kegiatan.tanggal_awal_jadwal
     *
     * @mbg.generated
     */
    public Date getTanggalAwalJadwal() {
        return tanggalAwalJadwal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.tanggal_awal_jadwal
     *
     * @param tanggalAwalJadwal the value for jadwal_kegiatan.tanggal_awal_jadwal
     *
     * @mbg.generated
     */
    public void setTanggalAwalJadwal(Date tanggalAwalJadwal) {
        this.tanggalAwalJadwal = tanggalAwalJadwal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.tanggal_akhir_jadwal
     *
     * @return the value of jadwal_kegiatan.tanggal_akhir_jadwal
     *
     * @mbg.generated
     */
    public Date getTanggalAkhirJadwal() {
        return tanggalAkhirJadwal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.tanggal_akhir_jadwal
     *
     * @param tanggalAkhirJadwal the value for jadwal_kegiatan.tanggal_akhir_jadwal
     *
     * @mbg.generated
     */
    public void setTanggalAkhirJadwal(Date tanggalAkhirJadwal) {
        this.tanggalAkhirJadwal = tanggalAkhirJadwal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.tahun
     *
     * @return the value of jadwal_kegiatan.tahun
     *
     * @mbg.generated
     */
    public Short getTahun() {
        return tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.tahun
     *
     * @param tahun the value for jadwal_kegiatan.tahun
     *
     * @mbg.generated
     */
    public void setTahun(Short tahun) {
        this.tahun = tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jadwal_kegiatan.nama_kegiatan
     *
     * @return the value of jadwal_kegiatan.nama_kegiatan
     *
     * @mbg.generated
     */
    public String getNamaKegiatan() {
        return namaKegiatan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jadwal_kegiatan.nama_kegiatan
     *
     * @param namaKegiatan the value for jadwal_kegiatan.nama_kegiatan
     *
     * @mbg.generated
     */
    public void setNamaKegiatan(String namaKegiatan) {
        this.namaKegiatan = namaKegiatan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jadwal_kegiatan
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        JadwalKegiatan other = (JadwalKegiatan) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdPenelitian() == null ? other.getIdPenelitian() == null : this.getIdPenelitian().equals(other.getIdPenelitian()))
            && (this.getTanggalAwalJadwal() == null ? other.getTanggalAwalJadwal() == null : this.getTanggalAwalJadwal().equals(other.getTanggalAwalJadwal()))
            && (this.getTanggalAkhirJadwal() == null ? other.getTanggalAkhirJadwal() == null : this.getTanggalAkhirJadwal().equals(other.getTanggalAkhirJadwal()))
            && (this.getTahun() == null ? other.getTahun() == null : this.getTahun().equals(other.getTahun()))
            && (this.getNamaKegiatan() == null ? other.getNamaKegiatan() == null : this.getNamaKegiatan().equals(other.getNamaKegiatan()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jadwal_kegiatan
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdPenelitian() == null) ? 0 : getIdPenelitian().hashCode());
        result = prime * result + ((getTanggalAwalJadwal() == null) ? 0 : getTanggalAwalJadwal().hashCode());
        result = prime * result + ((getTanggalAkhirJadwal() == null) ? 0 : getTanggalAkhirJadwal().hashCode());
        result = prime * result + ((getTahun() == null) ? 0 : getTahun().hashCode());
        result = prime * result + ((getNamaKegiatan() == null) ? 0 : getNamaKegiatan().hashCode());
        return result;
    }
}