package com.pusilkom.base.model;

import java.io.Serializable;

public class KontribusiMitra implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kontribusi_mitra.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kontribusi_mitra.id_mitra_penelitian
     *
     * @mbg.generated
     */
    private Integer idMitraPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kontribusi_mitra.tahun
     *
     * @mbg.generated
     */
    private Short tahun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kontribusi_mitra.jumlah_kontribusi
     *
     * @mbg.generated
     */
    private Integer jumlahKontribusi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kontribusi_mitra.barang_kontribusi
     *
     * @mbg.generated
     */
    private String barangKontribusi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kontribusi_mitra
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kontribusi_mitra.id
     *
     * @return the value of kontribusi_mitra.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kontribusi_mitra.id
     *
     * @param id the value for kontribusi_mitra.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kontribusi_mitra.id_mitra_penelitian
     *
     * @return the value of kontribusi_mitra.id_mitra_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdMitraPenelitian() {
        return idMitraPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kontribusi_mitra.id_mitra_penelitian
     *
     * @param idMitraPenelitian the value for kontribusi_mitra.id_mitra_penelitian
     *
     * @mbg.generated
     */
    public void setIdMitraPenelitian(Integer idMitraPenelitian) {
        this.idMitraPenelitian = idMitraPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kontribusi_mitra.tahun
     *
     * @return the value of kontribusi_mitra.tahun
     *
     * @mbg.generated
     */
    public Short getTahun() {
        return tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kontribusi_mitra.tahun
     *
     * @param tahun the value for kontribusi_mitra.tahun
     *
     * @mbg.generated
     */
    public void setTahun(Short tahun) {
        this.tahun = tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kontribusi_mitra.jumlah_kontribusi
     *
     * @return the value of kontribusi_mitra.jumlah_kontribusi
     *
     * @mbg.generated
     */
    public Integer getJumlahKontribusi() {
        return jumlahKontribusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kontribusi_mitra.jumlah_kontribusi
     *
     * @param jumlahKontribusi the value for kontribusi_mitra.jumlah_kontribusi
     *
     * @mbg.generated
     */
    public void setJumlahKontribusi(Integer jumlahKontribusi) {
        this.jumlahKontribusi = jumlahKontribusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kontribusi_mitra.barang_kontribusi
     *
     * @return the value of kontribusi_mitra.barang_kontribusi
     *
     * @mbg.generated
     */
    public String getBarangKontribusi() {
        return barangKontribusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kontribusi_mitra.barang_kontribusi
     *
     * @param barangKontribusi the value for kontribusi_mitra.barang_kontribusi
     *
     * @mbg.generated
     */
    public void setBarangKontribusi(String barangKontribusi) {
        this.barangKontribusi = barangKontribusi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kontribusi_mitra
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        KontribusiMitra other = (KontribusiMitra) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdMitraPenelitian() == null ? other.getIdMitraPenelitian() == null : this.getIdMitraPenelitian().equals(other.getIdMitraPenelitian()))
            && (this.getTahun() == null ? other.getTahun() == null : this.getTahun().equals(other.getTahun()))
            && (this.getJumlahKontribusi() == null ? other.getJumlahKontribusi() == null : this.getJumlahKontribusi().equals(other.getJumlahKontribusi()))
            && (this.getBarangKontribusi() == null ? other.getBarangKontribusi() == null : this.getBarangKontribusi().equals(other.getBarangKontribusi()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kontribusi_mitra
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdMitraPenelitian() == null) ? 0 : getIdMitraPenelitian().hashCode());
        result = prime * result + ((getTahun() == null) ? 0 : getTahun().hashCode());
        result = prime * result + ((getJumlahKontribusi() == null) ? 0 : getJumlahKontribusi().hashCode());
        result = prime * result + ((getBarangKontribusi() == null) ? 0 : getBarangKontribusi().hashCode());
        return result;
    }
}