package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.List;

public class OrganisasiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public OrganisasiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdTopikIsNull() {
            addCriterion("id_topik is null");
            return (Criteria) this;
        }

        public Criteria andIdTopikIsNotNull() {
            addCriterion("id_topik is not null");
            return (Criteria) this;
        }

        public Criteria andIdTopikEqualTo(Integer value) {
            addCriterion("id_topik =", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikNotEqualTo(Integer value) {
            addCriterion("id_topik <>", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikGreaterThan(Integer value) {
            addCriterion("id_topik >", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_topik >=", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikLessThan(Integer value) {
            addCriterion("id_topik <", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikLessThanOrEqualTo(Integer value) {
            addCriterion("id_topik <=", value, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikIn(List<Integer> values) {
            addCriterion("id_topik in", values, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikNotIn(List<Integer> values) {
            addCriterion("id_topik not in", values, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikBetween(Integer value1, Integer value2) {
            addCriterion("id_topik between", value1, value2, "idTopik");
            return (Criteria) this;
        }

        public Criteria andIdTopikNotBetween(Integer value1, Integer value2) {
            addCriterion("id_topik not between", value1, value2, "idTopik");
            return (Criteria) this;
        }

        public Criteria andNamaIsNull() {
            addCriterion("nama is null");
            return (Criteria) this;
        }

        public Criteria andNamaIsNotNull() {
            addCriterion("nama is not null");
            return (Criteria) this;
        }

        public Criteria andNamaEqualTo(String value) {
            addCriterion("nama =", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotEqualTo(String value) {
            addCriterion("nama <>", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThan(String value) {
            addCriterion("nama >", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThanOrEqualTo(String value) {
            addCriterion("nama >=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThan(String value) {
            addCriterion("nama <", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThanOrEqualTo(String value) {
            addCriterion("nama <=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLike(String value) {
            addCriterion("nama like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotLike(String value) {
            addCriterion("nama not like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaIn(List<String> values) {
            addCriterion("nama in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotIn(List<String> values) {
            addCriterion("nama not in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaBetween(String value1, String value2) {
            addCriterion("nama between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotBetween(String value1, String value2) {
            addCriterion("nama not between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianIsNull() {
            addCriterion("no_sk_pendirian is null");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianIsNotNull() {
            addCriterion("no_sk_pendirian is not null");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianEqualTo(String value) {
            addCriterion("no_sk_pendirian =", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianNotEqualTo(String value) {
            addCriterion("no_sk_pendirian <>", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianGreaterThan(String value) {
            addCriterion("no_sk_pendirian >", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianGreaterThanOrEqualTo(String value) {
            addCriterion("no_sk_pendirian >=", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianLessThan(String value) {
            addCriterion("no_sk_pendirian <", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianLessThanOrEqualTo(String value) {
            addCriterion("no_sk_pendirian <=", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianLike(String value) {
            addCriterion("no_sk_pendirian like", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianNotLike(String value) {
            addCriterion("no_sk_pendirian not like", value, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianIn(List<String> values) {
            addCriterion("no_sk_pendirian in", values, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianNotIn(List<String> values) {
            addCriterion("no_sk_pendirian not in", values, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianBetween(String value1, String value2) {
            addCriterion("no_sk_pendirian between", value1, value2, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianNotBetween(String value1, String value2) {
            addCriterion("no_sk_pendirian not between", value1, value2, "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNull() {
            addCriterion("alamat is null");
            return (Criteria) this;
        }

        public Criteria andAlamatIsNotNull() {
            addCriterion("alamat is not null");
            return (Criteria) this;
        }

        public Criteria andAlamatEqualTo(String value) {
            addCriterion("alamat =", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotEqualTo(String value) {
            addCriterion("alamat <>", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThan(String value) {
            addCriterion("alamat >", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatGreaterThanOrEqualTo(String value) {
            addCriterion("alamat >=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThan(String value) {
            addCriterion("alamat <", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLessThanOrEqualTo(String value) {
            addCriterion("alamat <=", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatLike(String value) {
            addCriterion("alamat like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotLike(String value) {
            addCriterion("alamat not like", value, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatIn(List<String> values) {
            addCriterion("alamat in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotIn(List<String> values) {
            addCriterion("alamat not in", values, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatBetween(String value1, String value2) {
            addCriterion("alamat between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andAlamatNotBetween(String value1, String value2) {
            addCriterion("alamat not between", value1, value2, "alamat");
            return (Criteria) this;
        }

        public Criteria andNoTelpIsNull() {
            addCriterion("no_telp is null");
            return (Criteria) this;
        }

        public Criteria andNoTelpIsNotNull() {
            addCriterion("no_telp is not null");
            return (Criteria) this;
        }

        public Criteria andNoTelpEqualTo(String value) {
            addCriterion("no_telp =", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpNotEqualTo(String value) {
            addCriterion("no_telp <>", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpGreaterThan(String value) {
            addCriterion("no_telp >", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpGreaterThanOrEqualTo(String value) {
            addCriterion("no_telp >=", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpLessThan(String value) {
            addCriterion("no_telp <", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpLessThanOrEqualTo(String value) {
            addCriterion("no_telp <=", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpLike(String value) {
            addCriterion("no_telp like", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpNotLike(String value) {
            addCriterion("no_telp not like", value, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpIn(List<String> values) {
            addCriterion("no_telp in", values, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpNotIn(List<String> values) {
            addCriterion("no_telp not in", values, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpBetween(String value1, String value2) {
            addCriterion("no_telp between", value1, value2, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoTelpNotBetween(String value1, String value2) {
            addCriterion("no_telp not between", value1, value2, "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoFaxIsNull() {
            addCriterion("no_fax is null");
            return (Criteria) this;
        }

        public Criteria andNoFaxIsNotNull() {
            addCriterion("no_fax is not null");
            return (Criteria) this;
        }

        public Criteria andNoFaxEqualTo(String value) {
            addCriterion("no_fax =", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxNotEqualTo(String value) {
            addCriterion("no_fax <>", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxGreaterThan(String value) {
            addCriterion("no_fax >", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxGreaterThanOrEqualTo(String value) {
            addCriterion("no_fax >=", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxLessThan(String value) {
            addCriterion("no_fax <", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxLessThanOrEqualTo(String value) {
            addCriterion("no_fax <=", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxLike(String value) {
            addCriterion("no_fax like", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxNotLike(String value) {
            addCriterion("no_fax not like", value, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxIn(List<String> values) {
            addCriterion("no_fax in", values, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxNotIn(List<String> values) {
            addCriterion("no_fax not in", values, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxBetween(String value1, String value2) {
            addCriterion("no_fax between", value1, value2, "noFax");
            return (Criteria) this;
        }

        public Criteria andNoFaxNotBetween(String value1, String value2) {
            addCriterion("no_fax not between", value1, value2, "noFax");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaIsNull() {
            addCriterion("nama_jabatan_kepala is null");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaIsNotNull() {
            addCriterion("nama_jabatan_kepala is not null");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaEqualTo(String value) {
            addCriterion("nama_jabatan_kepala =", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaNotEqualTo(String value) {
            addCriterion("nama_jabatan_kepala <>", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaGreaterThan(String value) {
            addCriterion("nama_jabatan_kepala >", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaGreaterThanOrEqualTo(String value) {
            addCriterion("nama_jabatan_kepala >=", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaLessThan(String value) {
            addCriterion("nama_jabatan_kepala <", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaLessThanOrEqualTo(String value) {
            addCriterion("nama_jabatan_kepala <=", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaLike(String value) {
            addCriterion("nama_jabatan_kepala like", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaNotLike(String value) {
            addCriterion("nama_jabatan_kepala not like", value, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaIn(List<String> values) {
            addCriterion("nama_jabatan_kepala in", values, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaNotIn(List<String> values) {
            addCriterion("nama_jabatan_kepala not in", values, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaBetween(String value1, String value2) {
            addCriterion("nama_jabatan_kepala between", value1, value2, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaNotBetween(String value1, String value2) {
            addCriterion("nama_jabatan_kepala not between", value1, value2, "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaIsNull() {
            addCriterion("nidn_pejabat_kepala is null");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaIsNotNull() {
            addCriterion("nidn_pejabat_kepala is not null");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaEqualTo(String value) {
            addCriterion("nidn_pejabat_kepala =", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaNotEqualTo(String value) {
            addCriterion("nidn_pejabat_kepala <>", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaGreaterThan(String value) {
            addCriterion("nidn_pejabat_kepala >", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaGreaterThanOrEqualTo(String value) {
            addCriterion("nidn_pejabat_kepala >=", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaLessThan(String value) {
            addCriterion("nidn_pejabat_kepala <", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaLessThanOrEqualTo(String value) {
            addCriterion("nidn_pejabat_kepala <=", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaLike(String value) {
            addCriterion("nidn_pejabat_kepala like", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaNotLike(String value) {
            addCriterion("nidn_pejabat_kepala not like", value, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaIn(List<String> values) {
            addCriterion("nidn_pejabat_kepala in", values, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaNotIn(List<String> values) {
            addCriterion("nidn_pejabat_kepala not in", values, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaBetween(String value1, String value2) {
            addCriterion("nidn_pejabat_kepala between", value1, value2, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaNotBetween(String value1, String value2) {
            addCriterion("nidn_pejabat_kepala not between", value1, value2, "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaIsNull() {
            addCriterion("nama_pejabat_kepala is null");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaIsNotNull() {
            addCriterion("nama_pejabat_kepala is not null");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaEqualTo(String value) {
            addCriterion("nama_pejabat_kepala =", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaNotEqualTo(String value) {
            addCriterion("nama_pejabat_kepala <>", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaGreaterThan(String value) {
            addCriterion("nama_pejabat_kepala >", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaGreaterThanOrEqualTo(String value) {
            addCriterion("nama_pejabat_kepala >=", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaLessThan(String value) {
            addCriterion("nama_pejabat_kepala <", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaLessThanOrEqualTo(String value) {
            addCriterion("nama_pejabat_kepala <=", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaLike(String value) {
            addCriterion("nama_pejabat_kepala like", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaNotLike(String value) {
            addCriterion("nama_pejabat_kepala not like", value, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaIn(List<String> values) {
            addCriterion("nama_pejabat_kepala in", values, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaNotIn(List<String> values) {
            addCriterion("nama_pejabat_kepala not in", values, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaBetween(String value1, String value2) {
            addCriterion("nama_pejabat_kepala between", value1, value2, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaNotBetween(String value1, String value2) {
            addCriterion("nama_pejabat_kepala not between", value1, value2, "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminIsNull() {
            addCriterion("jenis_kelamin is null");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminIsNotNull() {
            addCriterion("jenis_kelamin is not null");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminEqualTo(String value) {
            addCriterion("jenis_kelamin =", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminNotEqualTo(String value) {
            addCriterion("jenis_kelamin <>", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminGreaterThan(String value) {
            addCriterion("jenis_kelamin >", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminGreaterThanOrEqualTo(String value) {
            addCriterion("jenis_kelamin >=", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminLessThan(String value) {
            addCriterion("jenis_kelamin <", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminLessThanOrEqualTo(String value) {
            addCriterion("jenis_kelamin <=", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminLike(String value) {
            addCriterion("jenis_kelamin like", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminNotLike(String value) {
            addCriterion("jenis_kelamin not like", value, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminIn(List<String> values) {
            addCriterion("jenis_kelamin in", values, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminNotIn(List<String> values) {
            addCriterion("jenis_kelamin not in", values, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminBetween(String value1, String value2) {
            addCriterion("jenis_kelamin between", value1, value2, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminNotBetween(String value1, String value2) {
            addCriterion("jenis_kelamin not between", value1, value2, "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanIsNull() {
            addCriterion("jenjang_pendidikan is null");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanIsNotNull() {
            addCriterion("jenjang_pendidikan is not null");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanEqualTo(String value) {
            addCriterion("jenjang_pendidikan =", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanNotEqualTo(String value) {
            addCriterion("jenjang_pendidikan <>", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanGreaterThan(String value) {
            addCriterion("jenjang_pendidikan >", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanGreaterThanOrEqualTo(String value) {
            addCriterion("jenjang_pendidikan >=", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanLessThan(String value) {
            addCriterion("jenjang_pendidikan <", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanLessThanOrEqualTo(String value) {
            addCriterion("jenjang_pendidikan <=", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanLike(String value) {
            addCriterion("jenjang_pendidikan like", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanNotLike(String value) {
            addCriterion("jenjang_pendidikan not like", value, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanIn(List<String> values) {
            addCriterion("jenjang_pendidikan in", values, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanNotIn(List<String> values) {
            addCriterion("jenjang_pendidikan not in", values, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanBetween(String value1, String value2) {
            addCriterion("jenjang_pendidikan between", value1, value2, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanNotBetween(String value1, String value2) {
            addCriterion("jenjang_pendidikan not between", value1, value2, "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesIsNull() {
            addCriterion("is_poltekkes is null");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesIsNotNull() {
            addCriterion("is_poltekkes is not null");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesEqualTo(Boolean value) {
            addCriterion("is_poltekkes =", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesNotEqualTo(Boolean value) {
            addCriterion("is_poltekkes <>", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesGreaterThan(Boolean value) {
            addCriterion("is_poltekkes >", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_poltekkes >=", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesLessThan(Boolean value) {
            addCriterion("is_poltekkes <", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesLessThanOrEqualTo(Boolean value) {
            addCriterion("is_poltekkes <=", value, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesIn(List<Boolean> values) {
            addCriterion("is_poltekkes in", values, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesNotIn(List<Boolean> values) {
            addCriterion("is_poltekkes not in", values, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesBetween(Boolean value1, Boolean value2) {
            addCriterion("is_poltekkes between", value1, value2, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andIsPoltekkesNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_poltekkes not between", value1, value2, "isPoltekkes");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiIsNull() {
            addCriterion("klasifikasi is null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiIsNotNull() {
            addCriterion("klasifikasi is not null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiEqualTo(Short value) {
            addCriterion("klasifikasi =", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiNotEqualTo(Short value) {
            addCriterion("klasifikasi <>", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiGreaterThan(Short value) {
            addCriterion("klasifikasi >", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiGreaterThanOrEqualTo(Short value) {
            addCriterion("klasifikasi >=", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiLessThan(Short value) {
            addCriterion("klasifikasi <", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiLessThanOrEqualTo(Short value) {
            addCriterion("klasifikasi <=", value, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiIn(List<Short> values) {
            addCriterion("klasifikasi in", values, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiNotIn(List<Short> values) {
            addCriterion("klasifikasi not in", values, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiBetween(Short value1, Short value2) {
            addCriterion("klasifikasi between", value1, value2, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasiNotBetween(Short value1, Short value2) {
            addCriterion("klasifikasi not between", value1, value2, "klasifikasi");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNull() {
            addCriterion("website is null");
            return (Criteria) this;
        }

        public Criteria andWebsiteIsNotNull() {
            addCriterion("website is not null");
            return (Criteria) this;
        }

        public Criteria andWebsiteEqualTo(String value) {
            addCriterion("website =", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotEqualTo(String value) {
            addCriterion("website <>", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThan(String value) {
            addCriterion("website >", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteGreaterThanOrEqualTo(String value) {
            addCriterion("website >=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThan(String value) {
            addCriterion("website <", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLessThanOrEqualTo(String value) {
            addCriterion("website <=", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteLike(String value) {
            addCriterion("website like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotLike(String value) {
            addCriterion("website not like", value, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteIn(List<String> values) {
            addCriterion("website in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotIn(List<String> values) {
            addCriterion("website not in", values, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteBetween(String value1, String value2) {
            addCriterion("website between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andWebsiteNotBetween(String value1, String value2) {
            addCriterion("website not between", value1, value2, "website");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiIsNull() {
            addCriterion("kode_pddikti is null");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiIsNotNull() {
            addCriterion("kode_pddikti is not null");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiEqualTo(String value) {
            addCriterion("kode_pddikti =", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiNotEqualTo(String value) {
            addCriterion("kode_pddikti <>", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiGreaterThan(String value) {
            addCriterion("kode_pddikti >", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiGreaterThanOrEqualTo(String value) {
            addCriterion("kode_pddikti >=", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiLessThan(String value) {
            addCriterion("kode_pddikti <", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiLessThanOrEqualTo(String value) {
            addCriterion("kode_pddikti <=", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiLike(String value) {
            addCriterion("kode_pddikti like", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiNotLike(String value) {
            addCriterion("kode_pddikti not like", value, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiIn(List<String> values) {
            addCriterion("kode_pddikti in", values, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiNotIn(List<String> values) {
            addCriterion("kode_pddikti not in", values, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiBetween(String value1, String value2) {
            addCriterion("kode_pddikti between", value1, value2, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiNotBetween(String value1, String value2) {
            addCriterion("kode_pddikti not between", value1, value2, "kodePddikti");
            return (Criteria) this;
        }

        public Criteria andNamaLikeInsensitive(String value) {
            addCriterion("upper(nama) like", value.toUpperCase(), "nama");
            return (Criteria) this;
        }

        public Criteria andNoSkPendirianLikeInsensitive(String value) {
            addCriterion("upper(no_sk_pendirian) like", value.toUpperCase(), "noSkPendirian");
            return (Criteria) this;
        }

        public Criteria andAlamatLikeInsensitive(String value) {
            addCriterion("upper(alamat) like", value.toUpperCase(), "alamat");
            return (Criteria) this;
        }

        public Criteria andNoTelpLikeInsensitive(String value) {
            addCriterion("upper(no_telp) like", value.toUpperCase(), "noTelp");
            return (Criteria) this;
        }

        public Criteria andNoFaxLikeInsensitive(String value) {
            addCriterion("upper(no_fax) like", value.toUpperCase(), "noFax");
            return (Criteria) this;
        }

        public Criteria andEmailLikeInsensitive(String value) {
            addCriterion("upper(email) like", value.toUpperCase(), "email");
            return (Criteria) this;
        }

        public Criteria andNamaJabatanKepalaLikeInsensitive(String value) {
            addCriterion("upper(nama_jabatan_kepala) like", value.toUpperCase(), "namaJabatanKepala");
            return (Criteria) this;
        }

        public Criteria andNidnPejabatKepalaLikeInsensitive(String value) {
            addCriterion("upper(nidn_pejabat_kepala) like", value.toUpperCase(), "nidnPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andNamaPejabatKepalaLikeInsensitive(String value) {
            addCriterion("upper(nama_pejabat_kepala) like", value.toUpperCase(), "namaPejabatKepala");
            return (Criteria) this;
        }

        public Criteria andJenisKelaminLikeInsensitive(String value) {
            addCriterion("upper(jenis_kelamin) like", value.toUpperCase(), "jenisKelamin");
            return (Criteria) this;
        }

        public Criteria andJenjangPendidikanLikeInsensitive(String value) {
            addCriterion("upper(jenjang_pendidikan) like", value.toUpperCase(), "jenjangPendidikan");
            return (Criteria) this;
        }

        public Criteria andWebsiteLikeInsensitive(String value) {
            addCriterion("upper(website) like", value.toUpperCase(), "website");
            return (Criteria) this;
        }

        public Criteria andKodePddiktiLikeInsensitive(String value) {
            addCriterion("upper(kode_pddikti) like", value.toUpperCase(), "kodePddikti");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organisasi
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organisasi
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}