package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OutputExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table output
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table output
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table output
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public OutputExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table output
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputIsNull() {
            addCriterion("id_jenis_output is null");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputIsNotNull() {
            addCriterion("id_jenis_output is not null");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputEqualTo(Integer value) {
            addCriterion("id_jenis_output =", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputNotEqualTo(Integer value) {
            addCriterion("id_jenis_output <>", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputGreaterThan(Integer value) {
            addCriterion("id_jenis_output >", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_jenis_output >=", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputLessThan(Integer value) {
            addCriterion("id_jenis_output <", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputLessThanOrEqualTo(Integer value) {
            addCriterion("id_jenis_output <=", value, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputIn(List<Integer> values) {
            addCriterion("id_jenis_output in", values, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputNotIn(List<Integer> values) {
            addCriterion("id_jenis_output not in", values, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputBetween(Integer value1, Integer value2) {
            addCriterion("id_jenis_output between", value1, value2, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdJenisOutputNotBetween(Integer value1, Integer value2) {
            addCriterion("id_jenis_output not between", value1, value2, "idJenisOutput");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNull() {
            addCriterion("id_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNotNull() {
            addCriterion("id_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianEqualTo(Integer value) {
            addCriterion("id_penelitian =", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotEqualTo(Integer value) {
            addCriterion("id_penelitian <>", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThan(Integer value) {
            addCriterion("id_penelitian >", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian >=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThan(Integer value) {
            addCriterion("id_penelitian <", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian <=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIn(List<Integer> values) {
            addCriterion("id_penelitian in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotIn(List<Integer> values) {
            addCriterion("id_penelitian not in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian not between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andJudulIsNull() {
            addCriterion("judul is null");
            return (Criteria) this;
        }

        public Criteria andJudulIsNotNull() {
            addCriterion("judul is not null");
            return (Criteria) this;
        }

        public Criteria andJudulEqualTo(String value) {
            addCriterion("judul =", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotEqualTo(String value) {
            addCriterion("judul <>", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulGreaterThan(String value) {
            addCriterion("judul >", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulGreaterThanOrEqualTo(String value) {
            addCriterion("judul >=", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLessThan(String value) {
            addCriterion("judul <", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLessThanOrEqualTo(String value) {
            addCriterion("judul <=", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulLike(String value) {
            addCriterion("judul like", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotLike(String value) {
            addCriterion("judul not like", value, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulIn(List<String> values) {
            addCriterion("judul in", values, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotIn(List<String> values) {
            addCriterion("judul not in", values, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulBetween(String value1, String value2) {
            addCriterion("judul between", value1, value2, "judul");
            return (Criteria) this;
        }

        public Criteria andJudulNotBetween(String value1, String value2) {
            addCriterion("judul not between", value1, value2, "judul");
            return (Criteria) this;
        }

        public Criteria andPathFileIsNull() {
            addCriterion("path_file is null");
            return (Criteria) this;
        }

        public Criteria andPathFileIsNotNull() {
            addCriterion("path_file is not null");
            return (Criteria) this;
        }

        public Criteria andPathFileEqualTo(String value) {
            addCriterion("path_file =", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileNotEqualTo(String value) {
            addCriterion("path_file <>", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileGreaterThan(String value) {
            addCriterion("path_file >", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileGreaterThanOrEqualTo(String value) {
            addCriterion("path_file >=", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileLessThan(String value) {
            addCriterion("path_file <", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileLessThanOrEqualTo(String value) {
            addCriterion("path_file <=", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileLike(String value) {
            addCriterion("path_file like", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileNotLike(String value) {
            addCriterion("path_file not like", value, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileIn(List<String> values) {
            addCriterion("path_file in", values, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileNotIn(List<String> values) {
            addCriterion("path_file not in", values, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileBetween(String value1, String value2) {
            addCriterion("path_file between", value1, value2, "pathFile");
            return (Criteria) this;
        }

        public Criteria andPathFileNotBetween(String value1, String value2) {
            addCriterion("path_file not between", value1, value2, "pathFile");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadIsNull() {
            addCriterion("timestamp_upload is null");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadIsNotNull() {
            addCriterion("timestamp_upload is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadEqualTo(Date value) {
            addCriterion("timestamp_upload =", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadNotEqualTo(Date value) {
            addCriterion("timestamp_upload <>", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadGreaterThan(Date value) {
            addCriterion("timestamp_upload >", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadGreaterThanOrEqualTo(Date value) {
            addCriterion("timestamp_upload >=", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadLessThan(Date value) {
            addCriterion("timestamp_upload <", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadLessThanOrEqualTo(Date value) {
            addCriterion("timestamp_upload <=", value, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadIn(List<Date> values) {
            addCriterion("timestamp_upload in", values, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadNotIn(List<Date> values) {
            addCriterion("timestamp_upload not in", values, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadBetween(Date value1, Date value2) {
            addCriterion("timestamp_upload between", value1, value2, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andTimestampUploadNotBetween(Date value1, Date value2) {
            addCriterion("timestamp_upload not between", value1, value2, "timestampUpload");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiIsNull() {
            addCriterion("media_publikasi is null");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiIsNotNull() {
            addCriterion("media_publikasi is not null");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiEqualTo(String value) {
            addCriterion("media_publikasi =", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiNotEqualTo(String value) {
            addCriterion("media_publikasi <>", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiGreaterThan(String value) {
            addCriterion("media_publikasi >", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiGreaterThanOrEqualTo(String value) {
            addCriterion("media_publikasi >=", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiLessThan(String value) {
            addCriterion("media_publikasi <", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiLessThanOrEqualTo(String value) {
            addCriterion("media_publikasi <=", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiLike(String value) {
            addCriterion("media_publikasi like", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiNotLike(String value) {
            addCriterion("media_publikasi not like", value, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiIn(List<String> values) {
            addCriterion("media_publikasi in", values, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiNotIn(List<String> values) {
            addCriterion("media_publikasi not in", values, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiBetween(String value1, String value2) {
            addCriterion("media_publikasi between", value1, value2, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiNotBetween(String value1, String value2) {
            addCriterion("media_publikasi not between", value1, value2, "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiIsNull() {
            addCriterion("tanggal_publikasi is null");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiIsNotNull() {
            addCriterion("tanggal_publikasi is not null");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiEqualTo(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi =", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiNotEqualTo(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi <>", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiGreaterThan(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi >", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi >=", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiLessThan(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi <", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tanggal_publikasi <=", value, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiIn(List<Date> values) {
            addCriterionForJDBCDate("tanggal_publikasi in", values, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiNotIn(List<Date> values) {
            addCriterionForJDBCDate("tanggal_publikasi not in", values, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tanggal_publikasi between", value1, value2, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andTanggalPublikasiNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tanggal_publikasi not between", value1, value2, "tanggalPublikasi");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andJudulLikeInsensitive(String value) {
            addCriterion("upper(judul) like", value.toUpperCase(), "judul");
            return (Criteria) this;
        }

        public Criteria andPathFileLikeInsensitive(String value) {
            addCriterion("upper(path_file) like", value.toUpperCase(), "pathFile");
            return (Criteria) this;
        }

        public Criteria andMediaPublikasiLikeInsensitive(String value) {
            addCriterion("upper(media_publikasi) like", value.toUpperCase(), "mediaPublikasi");
            return (Criteria) this;
        }

        public Criteria andUrlLikeInsensitive(String value) {
            addCriterion("upper(url) like", value.toUpperCase(), "url");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table output
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table output
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}