package com.pusilkom.base.model;

import java.io.Serializable;

public class Prosiding implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prosiding.id_output
     *
     * @mbg.generated
     */
    private Integer idOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prosiding.nama_prosiding
     *
     * @mbg.generated
     */
    private String namaProsiding;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prosiding.tahun_prosiding
     *
     * @mbg.generated
     */
    private String tahunProsiding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prosiding
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prosiding.id_output
     *
     * @return the value of prosiding.id_output
     *
     * @mbg.generated
     */
    public Integer getIdOutput() {
        return idOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prosiding.id_output
     *
     * @param idOutput the value for prosiding.id_output
     *
     * @mbg.generated
     */
    public void setIdOutput(Integer idOutput) {
        this.idOutput = idOutput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prosiding.nama_prosiding
     *
     * @return the value of prosiding.nama_prosiding
     *
     * @mbg.generated
     */
    public String getNamaProsiding() {
        return namaProsiding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prosiding.nama_prosiding
     *
     * @param namaProsiding the value for prosiding.nama_prosiding
     *
     * @mbg.generated
     */
    public void setNamaProsiding(String namaProsiding) {
        this.namaProsiding = namaProsiding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prosiding.tahun_prosiding
     *
     * @return the value of prosiding.tahun_prosiding
     *
     * @mbg.generated
     */
    public String getTahunProsiding() {
        return tahunProsiding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prosiding.tahun_prosiding
     *
     * @param tahunProsiding the value for prosiding.tahun_prosiding
     *
     * @mbg.generated
     */
    public void setTahunProsiding(String tahunProsiding) {
        this.tahunProsiding = tahunProsiding;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prosiding
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Prosiding other = (Prosiding) that;
        return (this.getIdOutput() == null ? other.getIdOutput() == null : this.getIdOutput().equals(other.getIdOutput()))
            && (this.getNamaProsiding() == null ? other.getNamaProsiding() == null : this.getNamaProsiding().equals(other.getNamaProsiding()))
            && (this.getTahunProsiding() == null ? other.getTahunProsiding() == null : this.getTahunProsiding().equals(other.getTahunProsiding()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prosiding
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdOutput() == null) ? 0 : getIdOutput().hashCode());
        result = prime * result + ((getNamaProsiding() == null) ? 0 : getNamaProsiding().hashCode());
        result = prime * result + ((getTahunProsiding() == null) ? 0 : getTahunProsiding().hashCode());
        return result;
    }
}