package com.pusilkom.base.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class RencanaAnggaran implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.id_penelitian
     *
     * @mbg.generated
     */
    private Integer idPenelitian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.id_komponen_rab
     *
     * @mbg.generated
     */
    private Integer idKomponenRab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.tahun
     *
     * @mbg.generated
     */
    private Short tahun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.item
     *
     * @mbg.generated
     */
    private String item;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.volume
     *
     * @mbg.generated
     */
    private BigDecimal volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.satuan
     *
     * @mbg.generated
     */
    private String satuan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rencana_anggaran.biaya_satuan
     *
     * @mbg.generated
     */
    private BigDecimal biayaSatuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.id
     *
     * @return the value of rencana_anggaran.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.id
     *
     * @param id the value for rencana_anggaran.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.id_penelitian
     *
     * @return the value of rencana_anggaran.id_penelitian
     *
     * @mbg.generated
     */
    public Integer getIdPenelitian() {
        return idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.id_penelitian
     *
     * @param idPenelitian the value for rencana_anggaran.id_penelitian
     *
     * @mbg.generated
     */
    public void setIdPenelitian(Integer idPenelitian) {
        this.idPenelitian = idPenelitian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.id_komponen_rab
     *
     * @return the value of rencana_anggaran.id_komponen_rab
     *
     * @mbg.generated
     */
    public Integer getIdKomponenRab() {
        return idKomponenRab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.id_komponen_rab
     *
     * @param idKomponenRab the value for rencana_anggaran.id_komponen_rab
     *
     * @mbg.generated
     */
    public void setIdKomponenRab(Integer idKomponenRab) {
        this.idKomponenRab = idKomponenRab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.tahun
     *
     * @return the value of rencana_anggaran.tahun
     *
     * @mbg.generated
     */
    public Short getTahun() {
        return tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.tahun
     *
     * @param tahun the value for rencana_anggaran.tahun
     *
     * @mbg.generated
     */
    public void setTahun(Short tahun) {
        this.tahun = tahun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.item
     *
     * @return the value of rencana_anggaran.item
     *
     * @mbg.generated
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.item
     *
     * @param item the value for rencana_anggaran.item
     *
     * @mbg.generated
     */
    public void setItem(String item) {
        this.item = item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.volume
     *
     * @return the value of rencana_anggaran.volume
     *
     * @mbg.generated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.volume
     *
     * @param volume the value for rencana_anggaran.volume
     *
     * @mbg.generated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.satuan
     *
     * @return the value of rencana_anggaran.satuan
     *
     * @mbg.generated
     */
    public String getSatuan() {
        return satuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.satuan
     *
     * @param satuan the value for rencana_anggaran.satuan
     *
     * @mbg.generated
     */
    public void setSatuan(String satuan) {
        this.satuan = satuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rencana_anggaran.biaya_satuan
     *
     * @return the value of rencana_anggaran.biaya_satuan
     *
     * @mbg.generated
     */
    public BigDecimal getBiayaSatuan() {
        return biayaSatuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rencana_anggaran.biaya_satuan
     *
     * @param biayaSatuan the value for rencana_anggaran.biaya_satuan
     *
     * @mbg.generated
     */
    public void setBiayaSatuan(BigDecimal biayaSatuan) {
        this.biayaSatuan = biayaSatuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RencanaAnggaran other = (RencanaAnggaran) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdPenelitian() == null ? other.getIdPenelitian() == null : this.getIdPenelitian().equals(other.getIdPenelitian()))
            && (this.getIdKomponenRab() == null ? other.getIdKomponenRab() == null : this.getIdKomponenRab().equals(other.getIdKomponenRab()))
            && (this.getTahun() == null ? other.getTahun() == null : this.getTahun().equals(other.getTahun()))
            && (this.getItem() == null ? other.getItem() == null : this.getItem().equals(other.getItem()))
            && (this.getVolume() == null ? other.getVolume() == null : this.getVolume().equals(other.getVolume()))
            && (this.getSatuan() == null ? other.getSatuan() == null : this.getSatuan().equals(other.getSatuan()))
            && (this.getBiayaSatuan() == null ? other.getBiayaSatuan() == null : this.getBiayaSatuan().equals(other.getBiayaSatuan()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdPenelitian() == null) ? 0 : getIdPenelitian().hashCode());
        result = prime * result + ((getIdKomponenRab() == null) ? 0 : getIdKomponenRab().hashCode());
        result = prime * result + ((getTahun() == null) ? 0 : getTahun().hashCode());
        result = prime * result + ((getItem() == null) ? 0 : getItem().hashCode());
        result = prime * result + ((getVolume() == null) ? 0 : getVolume().hashCode());
        result = prime * result + ((getSatuan() == null) ? 0 : getSatuan().hashCode());
        result = prime * result + ((getBiayaSatuan() == null) ? 0 : getBiayaSatuan().hashCode());
        return result;
    }
}