package com.pusilkom.base.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RencanaAnggaranExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public RencanaAnggaranExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNull() {
            addCriterion("id_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIsNotNull() {
            addCriterion("id_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianEqualTo(Integer value) {
            addCriterion("id_penelitian =", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotEqualTo(Integer value) {
            addCriterion("id_penelitian <>", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThan(Integer value) {
            addCriterion("id_penelitian >", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian >=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThan(Integer value) {
            addCriterion("id_penelitian <", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_penelitian <=", value, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianIn(List<Integer> values) {
            addCriterion("id_penelitian in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotIn(List<Integer> values) {
            addCriterion("id_penelitian not in", values, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_penelitian not between", value1, value2, "idPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabIsNull() {
            addCriterion("id_komponen_rab is null");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabIsNotNull() {
            addCriterion("id_komponen_rab is not null");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabEqualTo(Integer value) {
            addCriterion("id_komponen_rab =", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabNotEqualTo(Integer value) {
            addCriterion("id_komponen_rab <>", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabGreaterThan(Integer value) {
            addCriterion("id_komponen_rab >", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_komponen_rab >=", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabLessThan(Integer value) {
            addCriterion("id_komponen_rab <", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabLessThanOrEqualTo(Integer value) {
            addCriterion("id_komponen_rab <=", value, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabIn(List<Integer> values) {
            addCriterion("id_komponen_rab in", values, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabNotIn(List<Integer> values) {
            addCriterion("id_komponen_rab not in", values, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabBetween(Integer value1, Integer value2) {
            addCriterion("id_komponen_rab between", value1, value2, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andIdKomponenRabNotBetween(Integer value1, Integer value2) {
            addCriterion("id_komponen_rab not between", value1, value2, "idKomponenRab");
            return (Criteria) this;
        }

        public Criteria andTahunIsNull() {
            addCriterion("tahun is null");
            return (Criteria) this;
        }

        public Criteria andTahunIsNotNull() {
            addCriterion("tahun is not null");
            return (Criteria) this;
        }

        public Criteria andTahunEqualTo(Short value) {
            addCriterion("tahun =", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunNotEqualTo(Short value) {
            addCriterion("tahun <>", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunGreaterThan(Short value) {
            addCriterion("tahun >", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunGreaterThanOrEqualTo(Short value) {
            addCriterion("tahun >=", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunLessThan(Short value) {
            addCriterion("tahun <", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunLessThanOrEqualTo(Short value) {
            addCriterion("tahun <=", value, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunIn(List<Short> values) {
            addCriterion("tahun in", values, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunNotIn(List<Short> values) {
            addCriterion("tahun not in", values, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunBetween(Short value1, Short value2) {
            addCriterion("tahun between", value1, value2, "tahun");
            return (Criteria) this;
        }

        public Criteria andTahunNotBetween(Short value1, Short value2) {
            addCriterion("tahun not between", value1, value2, "tahun");
            return (Criteria) this;
        }

        public Criteria andItemIsNull() {
            addCriterion("item is null");
            return (Criteria) this;
        }

        public Criteria andItemIsNotNull() {
            addCriterion("item is not null");
            return (Criteria) this;
        }

        public Criteria andItemEqualTo(String value) {
            addCriterion("item =", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotEqualTo(String value) {
            addCriterion("item <>", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemGreaterThan(String value) {
            addCriterion("item >", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemGreaterThanOrEqualTo(String value) {
            addCriterion("item >=", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLessThan(String value) {
            addCriterion("item <", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLessThanOrEqualTo(String value) {
            addCriterion("item <=", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemLike(String value) {
            addCriterion("item like", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotLike(String value) {
            addCriterion("item not like", value, "item");
            return (Criteria) this;
        }

        public Criteria andItemIn(List<String> values) {
            addCriterion("item in", values, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotIn(List<String> values) {
            addCriterion("item not in", values, "item");
            return (Criteria) this;
        }

        public Criteria andItemBetween(String value1, String value2) {
            addCriterion("item between", value1, value2, "item");
            return (Criteria) this;
        }

        public Criteria andItemNotBetween(String value1, String value2) {
            addCriterion("item not between", value1, value2, "item");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(BigDecimal value) {
            addCriterion("volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(BigDecimal value) {
            addCriterion("volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(BigDecimal value) {
            addCriterion("volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(BigDecimal value) {
            addCriterion("volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<BigDecimal> values) {
            addCriterion("volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<BigDecimal> values) {
            addCriterion("volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andSatuanIsNull() {
            addCriterion("satuan is null");
            return (Criteria) this;
        }

        public Criteria andSatuanIsNotNull() {
            addCriterion("satuan is not null");
            return (Criteria) this;
        }

        public Criteria andSatuanEqualTo(String value) {
            addCriterion("satuan =", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanNotEqualTo(String value) {
            addCriterion("satuan <>", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanGreaterThan(String value) {
            addCriterion("satuan >", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanGreaterThanOrEqualTo(String value) {
            addCriterion("satuan >=", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanLessThan(String value) {
            addCriterion("satuan <", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanLessThanOrEqualTo(String value) {
            addCriterion("satuan <=", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanLike(String value) {
            addCriterion("satuan like", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanNotLike(String value) {
            addCriterion("satuan not like", value, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanIn(List<String> values) {
            addCriterion("satuan in", values, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanNotIn(List<String> values) {
            addCriterion("satuan not in", values, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanBetween(String value1, String value2) {
            addCriterion("satuan between", value1, value2, "satuan");
            return (Criteria) this;
        }

        public Criteria andSatuanNotBetween(String value1, String value2) {
            addCriterion("satuan not between", value1, value2, "satuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanIsNull() {
            addCriterion("biaya_satuan is null");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanIsNotNull() {
            addCriterion("biaya_satuan is not null");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanEqualTo(BigDecimal value) {
            addCriterion("biaya_satuan =", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanNotEqualTo(BigDecimal value) {
            addCriterion("biaya_satuan <>", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanGreaterThan(BigDecimal value) {
            addCriterion("biaya_satuan >", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("biaya_satuan >=", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanLessThan(BigDecimal value) {
            addCriterion("biaya_satuan <", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanLessThanOrEqualTo(BigDecimal value) {
            addCriterion("biaya_satuan <=", value, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanIn(List<BigDecimal> values) {
            addCriterion("biaya_satuan in", values, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanNotIn(List<BigDecimal> values) {
            addCriterion("biaya_satuan not in", values, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("biaya_satuan between", value1, value2, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andBiayaSatuanNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("biaya_satuan not between", value1, value2, "biayaSatuan");
            return (Criteria) this;
        }

        public Criteria andItemLikeInsensitive(String value) {
            addCriterion("upper(item) like", value.toUpperCase(), "item");
            return (Criteria) this;
        }

        public Criteria andSatuanLikeInsensitive(String value) {
            addCriterion("upper(satuan) like", value.toUpperCase(), "satuan");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rencana_anggaran
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rencana_anggaran
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}