package com.pusilkom.base.model;

import java.util.ArrayList;
import java.util.List;

public class SkemaPenelitianExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public SkemaPenelitianExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianIsNull() {
            addCriterion("id_jenis_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianIsNotNull() {
            addCriterion("id_jenis_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianEqualTo(Integer value) {
            addCriterion("id_jenis_penelitian =", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianNotEqualTo(Integer value) {
            addCriterion("id_jenis_penelitian <>", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianGreaterThan(Integer value) {
            addCriterion("id_jenis_penelitian >", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_jenis_penelitian >=", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianLessThan(Integer value) {
            addCriterion("id_jenis_penelitian <", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_jenis_penelitian <=", value, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianIn(List<Integer> values) {
            addCriterion("id_jenis_penelitian in", values, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianNotIn(List<Integer> values) {
            addCriterion("id_jenis_penelitian not in", values, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_jenis_penelitian between", value1, value2, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdJenisPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_jenis_penelitian not between", value1, value2, "idJenisPenelitian");
            return (Criteria) this;
        }

        public Criteria andNamaIsNull() {
            addCriterion("nama is null");
            return (Criteria) this;
        }

        public Criteria andNamaIsNotNull() {
            addCriterion("nama is not null");
            return (Criteria) this;
        }

        public Criteria andNamaEqualTo(String value) {
            addCriterion("nama =", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotEqualTo(String value) {
            addCriterion("nama <>", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThan(String value) {
            addCriterion("nama >", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaGreaterThanOrEqualTo(String value) {
            addCriterion("nama >=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThan(String value) {
            addCriterion("nama <", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLessThanOrEqualTo(String value) {
            addCriterion("nama <=", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaLike(String value) {
            addCriterion("nama like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotLike(String value) {
            addCriterion("nama not like", value, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaIn(List<String> values) {
            addCriterion("nama in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotIn(List<String> values) {
            addCriterion("nama not in", values, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaBetween(String value1, String value2) {
            addCriterion("nama between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andNamaNotBetween(String value1, String value2) {
            addCriterion("nama not between", value1, value2, "nama");
            return (Criteria) this;
        }

        public Criteria andSingkatanIsNull() {
            addCriterion("singkatan is null");
            return (Criteria) this;
        }

        public Criteria andSingkatanIsNotNull() {
            addCriterion("singkatan is not null");
            return (Criteria) this;
        }

        public Criteria andSingkatanEqualTo(String value) {
            addCriterion("singkatan =", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanNotEqualTo(String value) {
            addCriterion("singkatan <>", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanGreaterThan(String value) {
            addCriterion("singkatan >", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanGreaterThanOrEqualTo(String value) {
            addCriterion("singkatan >=", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanLessThan(String value) {
            addCriterion("singkatan <", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanLessThanOrEqualTo(String value) {
            addCriterion("singkatan <=", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanLike(String value) {
            addCriterion("singkatan like", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanNotLike(String value) {
            addCriterion("singkatan not like", value, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanIn(List<String> values) {
            addCriterion("singkatan in", values, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanNotIn(List<String> values) {
            addCriterion("singkatan not in", values, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanBetween(String value1, String value2) {
            addCriterion("singkatan between", value1, value2, "singkatan");
            return (Criteria) this;
        }

        public Criteria andSingkatanNotBetween(String value1, String value2) {
            addCriterion("singkatan not between", value1, value2, "singkatan");
            return (Criteria) this;
        }

        public Criteria andDeskripsiIsNull() {
            addCriterion("deskripsi is null");
            return (Criteria) this;
        }

        public Criteria andDeskripsiIsNotNull() {
            addCriterion("deskripsi is not null");
            return (Criteria) this;
        }

        public Criteria andDeskripsiEqualTo(String value) {
            addCriterion("deskripsi =", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiNotEqualTo(String value) {
            addCriterion("deskripsi <>", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiGreaterThan(String value) {
            addCriterion("deskripsi >", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiGreaterThanOrEqualTo(String value) {
            addCriterion("deskripsi >=", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiLessThan(String value) {
            addCriterion("deskripsi <", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiLessThanOrEqualTo(String value) {
            addCriterion("deskripsi <=", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiLike(String value) {
            addCriterion("deskripsi like", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiNotLike(String value) {
            addCriterion("deskripsi not like", value, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiIn(List<String> values) {
            addCriterion("deskripsi in", values, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiNotIn(List<String> values) {
            addCriterion("deskripsi not in", values, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiBetween(String value1, String value2) {
            addCriterion("deskripsi between", value1, value2, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andDeskripsiNotBetween(String value1, String value2) {
            addCriterion("deskripsi not between", value1, value2, "deskripsi");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1IsNull() {
            addCriterion("klasifikasi_1 is null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1IsNotNull() {
            addCriterion("klasifikasi_1 is not null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1EqualTo(Boolean value) {
            addCriterion("klasifikasi_1 =", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1NotEqualTo(Boolean value) {
            addCriterion("klasifikasi_1 <>", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1GreaterThan(Boolean value) {
            addCriterion("klasifikasi_1 >", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1GreaterThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_1 >=", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1LessThan(Boolean value) {
            addCriterion("klasifikasi_1 <", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1LessThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_1 <=", value, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1In(List<Boolean> values) {
            addCriterion("klasifikasi_1 in", values, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1NotIn(List<Boolean> values) {
            addCriterion("klasifikasi_1 not in", values, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1Between(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_1 between", value1, value2, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi1NotBetween(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_1 not between", value1, value2, "klasifikasi1");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2IsNull() {
            addCriterion("klasifikasi_2 is null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2IsNotNull() {
            addCriterion("klasifikasi_2 is not null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2EqualTo(Boolean value) {
            addCriterion("klasifikasi_2 =", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2NotEqualTo(Boolean value) {
            addCriterion("klasifikasi_2 <>", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2GreaterThan(Boolean value) {
            addCriterion("klasifikasi_2 >", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2GreaterThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_2 >=", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2LessThan(Boolean value) {
            addCriterion("klasifikasi_2 <", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2LessThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_2 <=", value, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2In(List<Boolean> values) {
            addCriterion("klasifikasi_2 in", values, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2NotIn(List<Boolean> values) {
            addCriterion("klasifikasi_2 not in", values, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2Between(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_2 between", value1, value2, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi2NotBetween(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_2 not between", value1, value2, "klasifikasi2");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3IsNull() {
            addCriterion("klasifikasi_3 is null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3IsNotNull() {
            addCriterion("klasifikasi_3 is not null");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3EqualTo(Boolean value) {
            addCriterion("klasifikasi_3 =", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3NotEqualTo(Boolean value) {
            addCriterion("klasifikasi_3 <>", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3GreaterThan(Boolean value) {
            addCriterion("klasifikasi_3 >", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3GreaterThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_3 >=", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3LessThan(Boolean value) {
            addCriterion("klasifikasi_3 <", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3LessThanOrEqualTo(Boolean value) {
            addCriterion("klasifikasi_3 <=", value, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3In(List<Boolean> values) {
            addCriterion("klasifikasi_3 in", values, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3NotIn(List<Boolean> values) {
            addCriterion("klasifikasi_3 not in", values, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3Between(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_3 between", value1, value2, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andKlasifikasi3NotBetween(Boolean value1, Boolean value2) {
            addCriterion("klasifikasi_3 not between", value1, value2, "klasifikasi3");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianIsNull() {
            addCriterion("persyaratan_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianIsNotNull() {
            addCriterion("persyaratan_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianEqualTo(String value) {
            addCriterion("persyaratan_penelitian =", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianNotEqualTo(String value) {
            addCriterion("persyaratan_penelitian <>", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianGreaterThan(String value) {
            addCriterion("persyaratan_penelitian >", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianGreaterThanOrEqualTo(String value) {
            addCriterion("persyaratan_penelitian >=", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianLessThan(String value) {
            addCriterion("persyaratan_penelitian <", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianLessThanOrEqualTo(String value) {
            addCriterion("persyaratan_penelitian <=", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianLike(String value) {
            addCriterion("persyaratan_penelitian like", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianNotLike(String value) {
            addCriterion("persyaratan_penelitian not like", value, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianIn(List<String> values) {
            addCriterion("persyaratan_penelitian in", values, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianNotIn(List<String> values) {
            addCriterion("persyaratan_penelitian not in", values, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianBetween(String value1, String value2) {
            addCriterion("persyaratan_penelitian between", value1, value2, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianNotBetween(String value1, String value2) {
            addCriterion("persyaratan_penelitian not between", value1, value2, "persyaratanPenelitian");
            return (Criteria) this;
        }

        public Criteria andTktMinIsNull() {
            addCriterion("tkt_min is null");
            return (Criteria) this;
        }

        public Criteria andTktMinIsNotNull() {
            addCriterion("tkt_min is not null");
            return (Criteria) this;
        }

        public Criteria andTktMinEqualTo(Integer value) {
            addCriterion("tkt_min =", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinNotEqualTo(Integer value) {
            addCriterion("tkt_min <>", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinGreaterThan(Integer value) {
            addCriterion("tkt_min >", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("tkt_min >=", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinLessThan(Integer value) {
            addCriterion("tkt_min <", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinLessThanOrEqualTo(Integer value) {
            addCriterion("tkt_min <=", value, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinIn(List<Integer> values) {
            addCriterion("tkt_min in", values, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinNotIn(List<Integer> values) {
            addCriterion("tkt_min not in", values, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinBetween(Integer value1, Integer value2) {
            addCriterion("tkt_min between", value1, value2, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMinNotBetween(Integer value1, Integer value2) {
            addCriterion("tkt_min not between", value1, value2, "tktMin");
            return (Criteria) this;
        }

        public Criteria andTktMaxIsNull() {
            addCriterion("tkt_max is null");
            return (Criteria) this;
        }

        public Criteria andTktMaxIsNotNull() {
            addCriterion("tkt_max is not null");
            return (Criteria) this;
        }

        public Criteria andTktMaxEqualTo(Integer value) {
            addCriterion("tkt_max =", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxNotEqualTo(Integer value) {
            addCriterion("tkt_max <>", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxGreaterThan(Integer value) {
            addCriterion("tkt_max >", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("tkt_max >=", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxLessThan(Integer value) {
            addCriterion("tkt_max <", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxLessThanOrEqualTo(Integer value) {
            addCriterion("tkt_max <=", value, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxIn(List<Integer> values) {
            addCriterion("tkt_max in", values, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxNotIn(List<Integer> values) {
            addCriterion("tkt_max not in", values, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxBetween(Integer value1, Integer value2) {
            addCriterion("tkt_max between", value1, value2, "tktMax");
            return (Criteria) this;
        }

        public Criteria andTktMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("tkt_max not between", value1, value2, "tktMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinIsNull() {
            addCriterion("jumlah_pengusul_min is null");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinIsNotNull() {
            addCriterion("jumlah_pengusul_min is not null");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinEqualTo(Short value) {
            addCriterion("jumlah_pengusul_min =", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinNotEqualTo(Short value) {
            addCriterion("jumlah_pengusul_min <>", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinGreaterThan(Short value) {
            addCriterion("jumlah_pengusul_min >", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinGreaterThanOrEqualTo(Short value) {
            addCriterion("jumlah_pengusul_min >=", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinLessThan(Short value) {
            addCriterion("jumlah_pengusul_min <", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinLessThanOrEqualTo(Short value) {
            addCriterion("jumlah_pengusul_min <=", value, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinIn(List<Short> values) {
            addCriterion("jumlah_pengusul_min in", values, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinNotIn(List<Short> values) {
            addCriterion("jumlah_pengusul_min not in", values, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinBetween(Short value1, Short value2) {
            addCriterion("jumlah_pengusul_min between", value1, value2, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMinNotBetween(Short value1, Short value2) {
            addCriterion("jumlah_pengusul_min not between", value1, value2, "jumlahPengusulMin");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxIsNull() {
            addCriterion("jumlah_pengusul_max is null");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxIsNotNull() {
            addCriterion("jumlah_pengusul_max is not null");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxEqualTo(Short value) {
            addCriterion("jumlah_pengusul_max =", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxNotEqualTo(Short value) {
            addCriterion("jumlah_pengusul_max <>", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxGreaterThan(Short value) {
            addCriterion("jumlah_pengusul_max >", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxGreaterThanOrEqualTo(Short value) {
            addCriterion("jumlah_pengusul_max >=", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxLessThan(Short value) {
            addCriterion("jumlah_pengusul_max <", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxLessThanOrEqualTo(Short value) {
            addCriterion("jumlah_pengusul_max <=", value, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxIn(List<Short> values) {
            addCriterion("jumlah_pengusul_max in", values, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxNotIn(List<Short> values) {
            addCriterion("jumlah_pengusul_max not in", values, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxBetween(Short value1, Short value2) {
            addCriterion("jumlah_pengusul_max between", value1, value2, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJumlahPengusulMaxNotBetween(Short value1, Short value2) {
            addCriterion("jumlah_pengusul_max not between", value1, value2, "jumlahPengusulMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinIsNull() {
            addCriterion("jangka_waktu_min is null");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinIsNotNull() {
            addCriterion("jangka_waktu_min is not null");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinEqualTo(Short value) {
            addCriterion("jangka_waktu_min =", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinNotEqualTo(Short value) {
            addCriterion("jangka_waktu_min <>", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinGreaterThan(Short value) {
            addCriterion("jangka_waktu_min >", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinGreaterThanOrEqualTo(Short value) {
            addCriterion("jangka_waktu_min >=", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinLessThan(Short value) {
            addCriterion("jangka_waktu_min <", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinLessThanOrEqualTo(Short value) {
            addCriterion("jangka_waktu_min <=", value, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinIn(List<Short> values) {
            addCriterion("jangka_waktu_min in", values, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinNotIn(List<Short> values) {
            addCriterion("jangka_waktu_min not in", values, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinBetween(Short value1, Short value2) {
            addCriterion("jangka_waktu_min between", value1, value2, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMinNotBetween(Short value1, Short value2) {
            addCriterion("jangka_waktu_min not between", value1, value2, "jangkaWaktuMin");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxIsNull() {
            addCriterion("jangka_waktu_max is null");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxIsNotNull() {
            addCriterion("jangka_waktu_max is not null");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxEqualTo(Short value) {
            addCriterion("jangka_waktu_max =", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxNotEqualTo(Short value) {
            addCriterion("jangka_waktu_max <>", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxGreaterThan(Short value) {
            addCriterion("jangka_waktu_max >", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxGreaterThanOrEqualTo(Short value) {
            addCriterion("jangka_waktu_max >=", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxLessThan(Short value) {
            addCriterion("jangka_waktu_max <", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxLessThanOrEqualTo(Short value) {
            addCriterion("jangka_waktu_max <=", value, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxIn(List<Short> values) {
            addCriterion("jangka_waktu_max in", values, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxNotIn(List<Short> values) {
            addCriterion("jangka_waktu_max not in", values, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxBetween(Short value1, Short value2) {
            addCriterion("jangka_waktu_max between", value1, value2, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJangkaWaktuMaxNotBetween(Short value1, Short value2) {
            addCriterion("jangka_waktu_max not between", value1, value2, "jangkaWaktuMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinIsNull() {
            addCriterion("jumlah_dana_min is null");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinIsNotNull() {
            addCriterion("jumlah_dana_min is not null");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinEqualTo(Integer value) {
            addCriterion("jumlah_dana_min =", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinNotEqualTo(Integer value) {
            addCriterion("jumlah_dana_min <>", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinGreaterThan(Integer value) {
            addCriterion("jumlah_dana_min >", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("jumlah_dana_min >=", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinLessThan(Integer value) {
            addCriterion("jumlah_dana_min <", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinLessThanOrEqualTo(Integer value) {
            addCriterion("jumlah_dana_min <=", value, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinIn(List<Integer> values) {
            addCriterion("jumlah_dana_min in", values, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinNotIn(List<Integer> values) {
            addCriterion("jumlah_dana_min not in", values, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinBetween(Integer value1, Integer value2) {
            addCriterion("jumlah_dana_min between", value1, value2, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMinNotBetween(Integer value1, Integer value2) {
            addCriterion("jumlah_dana_min not between", value1, value2, "jumlahDanaMin");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxIsNull() {
            addCriterion("jumlah_dana_max is null");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxIsNotNull() {
            addCriterion("jumlah_dana_max is not null");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxEqualTo(Integer value) {
            addCriterion("jumlah_dana_max =", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxNotEqualTo(Integer value) {
            addCriterion("jumlah_dana_max <>", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxGreaterThan(Integer value) {
            addCriterion("jumlah_dana_max >", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("jumlah_dana_max >=", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxLessThan(Integer value) {
            addCriterion("jumlah_dana_max <", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxLessThanOrEqualTo(Integer value) {
            addCriterion("jumlah_dana_max <=", value, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxIn(List<Integer> values) {
            addCriterion("jumlah_dana_max in", values, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxNotIn(List<Integer> values) {
            addCriterion("jumlah_dana_max not in", values, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxBetween(Integer value1, Integer value2) {
            addCriterion("jumlah_dana_max between", value1, value2, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andJumlahDanaMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("jumlah_dana_max not between", value1, value2, "jumlahDanaMax");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianIsNull() {
            addCriterion("id_kategori_skema_penelitian is null");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianIsNotNull() {
            addCriterion("id_kategori_skema_penelitian is not null");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianEqualTo(Integer value) {
            addCriterion("id_kategori_skema_penelitian =", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianNotEqualTo(Integer value) {
            addCriterion("id_kategori_skema_penelitian <>", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianGreaterThan(Integer value) {
            addCriterion("id_kategori_skema_penelitian >", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_kategori_skema_penelitian >=", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianLessThan(Integer value) {
            addCriterion("id_kategori_skema_penelitian <", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianLessThanOrEqualTo(Integer value) {
            addCriterion("id_kategori_skema_penelitian <=", value, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianIn(List<Integer> values) {
            addCriterion("id_kategori_skema_penelitian in", values, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianNotIn(List<Integer> values) {
            addCriterion("id_kategori_skema_penelitian not in", values, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianBetween(Integer value1, Integer value2) {
            addCriterion("id_kategori_skema_penelitian between", value1, value2, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIdKategoriSkemaPenelitianNotBetween(Integer value1, Integer value2) {
            addCriterion("id_kategori_skema_penelitian not between", value1, value2, "idKategoriSkemaPenelitian");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatIsNull() {
            addCriterion("is_dikelola_pusat is null");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatIsNotNull() {
            addCriterion("is_dikelola_pusat is not null");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatEqualTo(Boolean value) {
            addCriterion("is_dikelola_pusat =", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatNotEqualTo(Boolean value) {
            addCriterion("is_dikelola_pusat <>", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatGreaterThan(Boolean value) {
            addCriterion("is_dikelola_pusat >", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_dikelola_pusat >=", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatLessThan(Boolean value) {
            addCriterion("is_dikelola_pusat <", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatLessThanOrEqualTo(Boolean value) {
            addCriterion("is_dikelola_pusat <=", value, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatIn(List<Boolean> values) {
            addCriterion("is_dikelola_pusat in", values, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatNotIn(List<Boolean> values) {
            addCriterion("is_dikelola_pusat not in", values, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatBetween(Boolean value1, Boolean value2) {
            addCriterion("is_dikelola_pusat between", value1, value2, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andIsDikelolaPusatNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_dikelola_pusat not between", value1, value2, "isDikelolaPusat");
            return (Criteria) this;
        }

        public Criteria andNamaLikeInsensitive(String value) {
            addCriterion("upper(nama) like", value.toUpperCase(), "nama");
            return (Criteria) this;
        }

        public Criteria andSingkatanLikeInsensitive(String value) {
            addCriterion("upper(singkatan) like", value.toUpperCase(), "singkatan");
            return (Criteria) this;
        }

        public Criteria andDeskripsiLikeInsensitive(String value) {
            addCriterion("upper(deskripsi) like", value.toUpperCase(), "deskripsi");
            return (Criteria) this;
        }

        public Criteria andPersyaratanPenelitianLikeInsensitive(String value) {
            addCriterion("upper(persyaratan_penelitian) like", value.toUpperCase(), "persyaratanPenelitian");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skema_penelitian
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skema_penelitian
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}