package com.pusilkom.base.model;

import java.io.Serializable;

public class Topik implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topik.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topik.id_tema
     *
     * @mbg.generated
     */
    private Integer idTema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topik.nama
     *
     * @mbg.generated
     */
    private String nama;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topik.is_active
     *
     * @mbg.generated
     */
    private Boolean isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topik
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topik.id
     *
     * @return the value of topik.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topik.id
     *
     * @param id the value for topik.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topik.id_tema
     *
     * @return the value of topik.id_tema
     *
     * @mbg.generated
     */
    public Integer getIdTema() {
        return idTema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topik.id_tema
     *
     * @param idTema the value for topik.id_tema
     *
     * @mbg.generated
     */
    public void setIdTema(Integer idTema) {
        this.idTema = idTema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topik.nama
     *
     * @return the value of topik.nama
     *
     * @mbg.generated
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topik.nama
     *
     * @param nama the value for topik.nama
     *
     * @mbg.generated
     */
    public void setNama(String nama) {
        this.nama = nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topik.is_active
     *
     * @return the value of topik.is_active
     *
     * @mbg.generated
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topik.is_active
     *
     * @param isActive the value for topik.is_active
     *
     * @mbg.generated
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topik
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Topik other = (Topik) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdTema() == null ? other.getIdTema() == null : this.getIdTema().equals(other.getIdTema()))
            && (this.getNama() == null ? other.getNama() == null : this.getNama().equals(other.getNama()))
            && (this.getIsActive() == null ? other.getIsActive() == null : this.getIsActive().equals(other.getIsActive()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topik
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdTema() == null) ? 0 : getIdTema().hashCode());
        result = prime * result + ((getNama() == null) ? 0 : getNama().hashCode());
        result = prime * result + ((getIsActive() == null) ? 0 : getIsActive().hashCode());
        return result;
    }
}